// ── TOP SECRET FC · Noticias compartidas ────────────────────────────────────
// Orden: más reciente primero. Agregar nuevas noticias al inicio del array.

const NOTICIAS = [
  {
    id: 'destacados-semana1-t2',
    pinned: false,
    category: 'Destacados',
    title: 'Semana 1 de Temporada 2: análisis de los tres frentes',
    date: '2026-05-22',
    dateLabel: '22 de mayo de 2026',
    excerpt: '16 partidos en 9 días. Arranque duro en la VPN, sólido en VPUG y casi perfecto en 11x11. Un repaso por el rendimiento colectivo de la primera semana de la nueva era.',
    image: 'logos/Destacados Sem1.png',
    body: [
      'Entre el 13 y el 21 de mayo, Top Secret FC completó su primera semana de competencia en la Temporada 2. <strong>16 partidos en 9 días</strong>, repartidos en tres ligas con exigencias distintas y resultados muy diferentes entre sí.',
      '<strong>VPN — El golpe de realidad.</strong> Nueve partidos, cero victorias, un empate y ocho derrotas. El salto a Primera División es exigente y los números lo confirman: en la mayoría de los encuentros el equipo mantuvo la pelota (entre el 53% y el 70% de posesión) y llegó con volumen al área, pero la efectividad no acompañó y la solidez defensiva fue irregular. El único punto llegó en el cierre de la tercera jornada, un empate 1-1 ante Riestra eSports con gol de BlackPanther. La VPN es el desafío pendiente de la temporada.',
      '<strong>VPUG — El mejor frente de la semana.</strong> Cuatro partidos, tres victorias. La semana arrancó con una goleada 3-0 de visitante ante United Mito —70% de posesión, precisión perfecta en los tiros— y siguió con un triunfo 2-0 ante Olimpo eSports, donde Alexisraies2 convirtió los dos tantos. La única caída fue ante All Boys (1-2) en casa, aunque el equipo respondió de inmediato con la victoria más emotiva de la semana: la remontada 3-2 sobre InfinitX el miércoles, con Lautavester7 anotando el gol del empate y la victoria. ciprimancini fue la figura de la jornada inaugural con 9.0 de rating.',
      '<strong>11x11 — Valla baja, resultados altos.</strong> Cuatro partidos, tres victorias y apenas dos goles recibidos en toda la semana. El equipo perdió el primer duelo ante Los Waxiturros (1-2) pero reaccionó en el mismo día con un triunfo 2-1 de visitante sobre Argentino de Merlo. El miércoles se completaron dos victorias consecutivas: 1-0 a Ferro eSp y 1-0 a Dep. Ballester, con Buraa 07 (7.8) y AR ELTIO (8.4) como figuras respectivas. La defensa fue la base: 21 entradas completadas ante Ferro, 17 ante Ballester con solo un gol concedido en el partido contra Merlo.',
      'En el plano individual, <strong>Lautavester7</strong> cerró la semana con 12 goles entre las tres ligas y es la referencia ofensiva del plantel. <strong>BlackPanther</strong> anotó en VPN, VPUG y 11x11 —8 goles en total— siendo el único jugador con presencia en el marcador de los tres torneos. <strong>J. Martinez</strong> disputó los 16 partidos, acumulando hasta 19.8 km recorridos en una sola noche, y mantuvo rating por encima de 7 en prácticamente todos los encuentros.',
      'Semana 1 completada. La Temporada 2 tiene forma. 🖤⭐',
    ],
    shareCaption: '🖤 SEMANA 1 · TEMPORADA 2 · TOP SECRET FC\n\n16 partidos · 3 ligas · 9 días\n\nVPN: 0V · 1E · 8D — arranque duro en la élite\nVPUG: 3V · 0E · 1D — sólidos\n11x11: 3V · 0E · 1D — valla baja, resultados altos\n\nLautavester7: 12 goles · BlackPanther: 8 goles en 3 ligas\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 SEMANA 1 · TEMPORADA 2\n\n16 partidos. Tres ligas. Un balance real:\n\nVPN 0-1-8 · VPUG 3-0-1 · 11x11 3-0-1\n\nLautavester7: 12G · BlackPanther: 8G en las 3 ligas · ciprimancini: 9.0 rating\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
      x:  '🖤 Semana 1 de Temporada 2 completada.\n\nVPN 0-1-8 · VPUG 3-0-1 · 11x11 3-0-1\n\n16 partidos en 9 días. La nueva era arrancó.\n\n#TopSecretFC #VPN #VPUG #11x11',
      fb: '🖤 SEMANA 1 · TEMPORADA 2 · TOP SECRET FC\n\nBalance de la primera semana en tres competencias:\n\n📊 VPN: 0 victorias · 1 empate · 8 derrotas — arranque duro en Primera División\n📊 VPUG: 3 victorias · 0 empates · 1 derrota — sólidos\n📊 11x11: 3 victorias · 0 empates · 1 derrota — valla baja, resultados altos\n\nLautavester7 cerró la semana con 12 goles entre las tres ligas. BlackPanther anotó en los tres torneos (8 goles en total). J. Martinez jugó los 16 partidos.\n\nLa Temporada 2 tiene forma. 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    },
  },
  {
    id: 'nuevo-ct-2026',
    pinned: false,
    category: 'Institucional',
    title: 'Top Secret FC presenta su nuevo Cuerpo Técnico',
    date: '2026-05-15',
    dateLabel: '15 de mayo de 2026',
    excerpt: 'Top Secret FC anuncia la conformación oficial de su nuevo Cuerpo Técnico. Cinco nombres, cinco roles, una sola dirección: llevar al club a lo más alto de la Primera División.',
    image: 'logos/Nuevo CT.png',
    body: [
      'Top Secret FC hace oficial la conformación de su nuevo Cuerpo Técnico de cara a la Temporada 2. Cinco integrantes, roles bien definidos y una convicción compartida: este club tiene todo para competirle a cualquiera en la élite del fútbol virtual argentino.',
      '<strong>#6 · Juan_Martinez4 — Director Técnico.</strong> El cerebro del equipo asume la conducción táctica. Define sistemas, gestiona el plantel y toma las decisiones que marcan el rumbo de cada partido. La pelota en el centro de la mesa no es casual.',
      '<strong>#32 · CipriMancini — Analista Táctico.</strong> El encargado de estudiar a los rivales antes de cada fecha. Lectura del juego, informes de video y propuestas para neutralizar al oponente. La preparación empieza antes de conectarse.',
      '<strong>#20 · Guiidow — Preparador Físico y Rendimiento.</strong> Gestiona la rotación del plantel, el estado de forma de cada jugador y los tiempos de carga y descanso durante la temporada. La base de un equipo competitivo es llegar siempre al cien.',
      '<strong>#7 · Lautavester7 — Entrenador de Línea Ofensiva.</strong> Especialista en patrones de ataque, combinaciones y pressing alto. Su experiencia como uno de los delanteros más letales del club convierte su mirada en un recurso invaluable para la línea de ataque.',
      '<strong>#30 · zPibu__ — Coordinador de Plantel y Mercado.</strong> Maneja la comunicación interna del grupo, la disponibilidad de jugadores para cada convocatoria y el seguimiento del mercado. El vínculo entre lo que pasa adentro y lo que se proyecta hacia afuera.',
      'Cinco roles distintos, mismo objetivo. El Cuerpo Técnico de Top Secret FC ya está trabajando. 🖤⭐',
    ],
    shareCaption: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nPresentamos oficialmente al CT que conducirá al club en la Temporada 2:\n\n📋 DT: Juan_Martinez4\n🔍 Analista: CipriMancini\n💪 Físico: Guiidow\n⚡ Ataque: Lautavester7\n🗂️ Coordinador: zPibu__\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
    shareCaptions: {
      ig: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nPresentamos oficialmente al CT que conducirá al club en la Temporada 2.\n\n📋 DT: Juan_Martinez4 · Analista: CipriMancini · Físico: Guiidow · Ataque: Lautavester7 · Coordinador: zPibu__\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
      x:  '🖤 Top Secret FC presenta su nuevo Cuerpo Técnico para la Temporada 2.\n\nDT: Juan_Martinez4 · Analista: CipriMancini · Físico: Guiidow · Ataque: Lautavester7 · Coordinador: zPibu__\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
      fb: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nEl club presenta oficialmente al Cuerpo Técnico que conducirá al equipo en la Temporada 2. Cinco integrantes, roles bien definidos, mismo objetivo.\n\n📋 DT: Juan_Martinez4\n🔍 Analista Táctico: CipriMancini\n💪 Preparador Físico: Guiidow\n⚡ Entrenador de Ataque: Lautavester7\n🗂️ Coordinador de Plantel: zPibu__\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
    },
  },
  {
    id: 'fixture-vpn-t2-2026',
    pinned: false,
    category: 'Fixture',
    title: 'Ya tenemos fixture: 19 partidos en la Primera División VPN',
    date: '2026-05-13',
    dateLabel: '13 de mayo de 2026',
    excerpt: 'La Liga VPN publicó el calendario oficial de la Temporada 2. Top Secret FC jugará 19 partidos en su debut en Primera División, con el primer partido hoy mismo.',
    image: 'logos/Fixture VPN.webp',
    body: [
      'Ya está oficial. La Liga VPN publicó el calendario completo de la Temporada 2 y Top Secret FC tiene por delante 19 partidos en su primera experiencia en la élite del fútbol virtual argentino.',
      'El debut es hoy: tres encuentros en una misma jornada frente a <strong>Escuela Vieja</strong> (Local · 23:00), <strong>Nueva Chicago eSports</strong> (Visita · 23:30) y <strong>Real Black</strong> (Local · 23:59). Un arranque exigente que marcará el tono de lo que viene.',
      'El fixture se extiende hasta el <strong>8 de junio</strong> con rivales de primer nivel: Comunicaciones, San Lorenzo Esports, Instituto Esports, Estudiantes LP, Talleres Esports, Belgrano Esports y más. Diecinueve jornadas que pondrán a prueba el nivel del plantel en la categoría más competitiva de la VPN Argentina.',
      'El desafío es histórico. Es la primera vez que Top Secret FC compite en Primera División y el club llega con un plantel renovado, hambre de demostrar y la convicción de que puede competirle a cualquiera.',
      'El fixture completo está disponible en el calendario del sitio. Confirmá tu asistencia para cada partido y seguí de cerca cada resultado. 🖤⭐',
    ],
    shareCaption: '📋 FIXTURE OFICIAL · TEMPORADA 2\n\nTop Secret FC ya tiene calendario en la Primera División VPN:\n\n🗓️ 19 partidos\n📅 13 mayo → 8 junio\n🏆 VPN Argentina · Primera División\n\nEl debut es HOY. ¡Vamos! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision',
    shareCaptions: {
      ig: '📋 FIXTURE OFICIAL · TEMPORADA 2 🖤\n\n19 partidos. 7 fechas. Primera División VPN.\n\nEl debut es HOY ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #PrimeraDivision #EAFCClubsPro #Fixture',
      x:  '📋 Ya tenemos fixture en Primera División VPN.\n\n19 partidos entre el 13/05 y el 08/06.\n\nEl debut es hoy 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #PrimeraDivision',
      fb: '📋 FIXTURE OFICIAL · TEMPORADA 2\n\nLa Liga VPN publicó el calendario completo y Top Secret FC tiene 19 partidos por delante en su debut en Primera División.\n\n🗓️ 13 de mayo al 8 de junio\n🏆 VPN Argentina · Primera División\n\nEl primer partido es hoy. ¡Vamos Top Secret FC! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #EAFCClubsPro',
    },
  },
  {
    id: 'plantel-2026',
    pinned: false,
    category: 'Plantel',
    title: 'Este es el plantel que jugará la nueva temporada',
    date: '2026-05-11',
    dateLabel: '11 de mayo de 2026',
    excerpt: 'Top Secret FC presenta oficialmente el plantel para la temporada 2026. Dieciséis jugadores, una misma misión: competir en la élite del fútbol virtual argentino.',
    image: 'logos/Plantel T2 2026.webp',
    body: [
      'Top Secret FC presenta el plantel que defenderá los colores del club en la temporada 2026. Dieciséis jugadores comprometidos con el proyecto, con historia dentro de la institución y con hambre de seguir creciendo.',
      'El bloque viene reforzado. A la base que logró el ascenso se suman tres incorporaciones que elevan la competencia interna y dan mayor profundidad en todas las líneas. El desafío es enorme — Primera División de la VPN — y el plantel está a la altura.',
      'En el arco, <strong>pauloco10 (#19)</strong> y <strong>Woolfyboyzx2 (#45)</strong> se disputan el puesto de titular. Atrás, <strong>Alexisraies23 (#3)</strong>, <strong>Cabers14 (#4)</strong>, <strong>AR-ELTIO (#21)</strong> y <strong>Agubostero7 (#31)</strong> forman una defensa sólida, mientras que <strong>Huber236 (#8)</strong> y <strong>zPibu__ (#30)</strong> cubren los laterales.',
      'En el mediocampo, <strong>Juan_Martinez4 (#6)</strong>, <strong>RS32-DaniStone (#13)</strong>, <strong>CipriMancini (#32)</strong>, <strong>Buraa07 (#5)</strong> y <strong>Guiidow (#20)</strong> ofrecen variantes tácticas y físicas para cualquier sistema.',
      'Arriba, la línea de ataque sigue siendo letal: <strong>BlackPanther-CG (#11)</strong>, <strong>Lautavester7 (#7)</strong> y <strong>Lucasmati_akd (#9)</strong> son los encargados de romper redes en la categoría más competitiva del fútbol virtual argentino.',
      '16 jugadores. Una identidad. Bienvenidos a la nueva era de Top Secret FC. 🖤⭐',
    ],
    shareCaption: '🖤 TOP SECRET FC · PLANTEL 2026\n\nEste es el equipo que jugará la nueva temporada:\n\n🧤 #19 pauloco10 · #45 Woolfyboyzx2\n🔒 #3 Alexisraies23 · #4 Cabers14 · #21 AR-ELTIO · #31 Agubostero7\n↔️ #8 Huber236 · #30 zPibu__\n⚙️ #6 Juan_Martinez4 · #13 RS32-DaniStone · #32 CipriMancini · #5 Buraa07 · #20 Guiidow\n⚡ #11 BlackPanther-CG · #7 Lautavester7 · #9 Lucasmati_akd\n\n16 jugadores. Una misión. ⭐\n\n#TopSecretFC #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 PLANTEL 2026 · TOP SECRET FC\n\n16 jugadores. Una identidad. Una misión. ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
      x:  '🖤 Top Secret FC presenta el plantel 2026.\n\n16 jugadores listos para la élite del fútbol virtual argentino ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
      fb: '🖤 PLANTEL 2026 · TOP SECRET FC\n\nEl club presenta oficialmente el plantel para la nueva temporada. Dieciséis jugadores comprometidos con el proyecto y listos para competir en la Primera División de la VPN.\n\n16 jugadores. Una identidad. Una misión. 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
    },
  },
  {
    id: 'fichajes-t2-2026',
    pinned: false,
    category: 'Mercado',
    title: 'Tres incorporaciones para la Temporada 2',
    date: '2026-05-10',
    dateLabel: '10 de mayo de 2026',
    excerpt: 'Top Secret FC anuncia las altas para la nueva temporada: Cabers14, pauloco10 y AR-ELTIO se suman al plantel. Nuevo Secreto. Misma Misión.',
    image: 'logos/Fichajes.webp',
    body: [
      'Top Secret FC cierra su ventana de mercado para la Temporada 2 con tres incorporaciones que refuerzan el plantel de cara al debut en la Primera División de la VPN.',
      '<strong>#4 · Cabers14</strong> llega para puntalar la línea defensiva. Defensa central con presencia y capacidad para liderar la última línea en una categoría más exigente.',
      '<strong>#19 · pauloco10</strong> es la gran apuesta del club. Portero con un perfil moderno que llega a ocupar el arco en una categoría que exige reacciones al máximo nivel.',
      '<strong>#21 · AR-ELTIO</strong> completa el bloque defensivo. Su incorporación da más profundidad al backline y permite al cuerpo técnico rotar sin resignar intensidad.',
      'Las tres altas consolidan un plantel con mayor amplitud y competencia en cada línea. El mensaje es claro: <em>Nuevo Secreto. Misma Misión.</em>',
    ],
    shareCaption: '🖤 FICHAJES · TOP SECRET FC\n\nTres incorporaciones para la Temporada 2:\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión. ⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 NUEVAS INCORPORACIONES · TOP SECRET FC\n\nTres refuerzos para la Temporada 2 ⭐\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión.\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Fichajes #EAFCClubsPro #NuevaTemporada',
      x:  '🖤 Top Secret FC anuncia tres incorporaciones para la Temporada 2.\n\n🔒 Cabers14 · pauloco10 · AR-ELTIO\n\nNuevo Secreto. Misma Misión. ⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
      fb: '🖤 FICHAJES · TOP SECRET FC\n\nEl club cierra su mercado para la Temporada 2 con tres incorporaciones que refuerzan defensiva y portería de cara al debut en Primera División VPN.\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión. 🖤⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
    },
  },
  {
    id: 'kit-drop-2026',
    pinned: false,
    category: 'Indumentaria',
    title: 'Nuevas camisetas para la temporada 2026',
    date: '2026-05-06',
    dateLabel: '6 de mayo de 2026',
    excerpt: 'Top Secret FC presenta el nuevo kit oficial para la temporada 2026. Las camisetas que nos acompañarán en la VPN, la VPUG y el 11x11.',
    image: 'logos/2026 Kit Drop.png',
    body: [
      'Top Secret FC presenta oficialmente el nuevo kit para la temporada 2026. Un diseño que llega con fuerza en un momento especial: el debut del club en la Primera División de la VPN.',
      'Las nuevas camisetas nos acompañarán en todas las competencias del ciclo: la Liga VPN, la VPUG y el 11x11. Tres frentes, una sola identidad.',
      'El kit es más que indumentaria. Es la imagen con la que salimos a la cancha, la que representa al club en cada partido y en cada foto. Este diseño está a la altura del momento.',
      '¡A lucirlas en la cancha! 🖤⭐',
    ],
    shareCaption: '👕 NUEVAS CAMISETAS · TOP SECRET FC\n\nPresentamos el kit oficial para la temporada 2026 🖤⭐\n\nVPN · VPUG · 11x11\n\nSeguinos → @fctopsecret en IG y X · fb.com/topsecretfc\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
    shareCaptions: {
      ig: '👕 KIT DROP 2026 · TOP SECRET FC\n\nNuevas camisetas para una nueva era 🖤⭐\n\nVPN · VPUG · 11x11\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro #NuevaTemporada',
      x:  '👕 Top Secret FC presenta el kit oficial 2026.\n\nTres ligas, una identidad 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
      fb: '👕 NUEVAS CAMISETAS · TOP SECRET FC\n\nPresentamos el kit oficial para la temporada 2026. Las camisetas que nos acompañarán en la VPN, la VPUG y el 11x11.\n\nUn diseño a la altura de la nueva era del club 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
    },
  },
  {
    id: 'rebrand-2026',
    pinned: false,
    category: 'Institucional',
    title: 'Top Secret FC presenta su nueva identidad',
    date: '2026-05-06',
    dateLabel: '6 de mayo de 2026',
    excerpt: 'El club anuncia una renovación de su identidad visual. Una nueva era para Top Secret FC.',
    image: 'logos/Anuncio Rebrand.webp',
    body: [
      'Top Secret FC da un paso adelante y presenta oficialmente su nueva identidad visual. Un rediseño que refleja la evolución del club y su crecimiento dentro del fútbol virtual argentino.',
      'La nueva imagen llega en un momento bisagra: el club acaba de lograr el ascenso a la Primera División de la VPN y se prepara para debutar en la élite del fútbol virtual argentino.',
      'El rebrand es más que un cambio estético. Representa la ambición del club, su identidad y el camino que tiene por delante.',
      'Seguinos en nuestras redes: <a href="https://instagram.com/fctopsecret" target="_blank" rel="noopener">Instagram</a> · <a href="https://x.com/fctopsecret" target="_blank" rel="noopener">X</a> · <a href="https://facebook.com/topsecretfc" target="_blank" rel="noopener">Facebook</a>',
      '¡Bienvenidos a la nueva era de Top Secret FC!',
    ],
    shareCaption: '⭐ TOP SECRET FC · NUEVA IDENTIDAD\n\nEl club presenta su nueva imagen. Una nueva era comienza.\n\n📱 @fctopsecret en IG y X · fb.com/topsecretfc\n\n🖤⭐ #TopSecretFC #Rebrand #EAFCClubsPro',
    shareCaptions: {
      ig: '⭐ NUEVA IDENTIDAD · TOP SECRET FC\n\nEvolucionamos. Presentamos nuestra nueva imagen 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Rebrand #EAFCClubsPro',
      x:  '⭐ Top Secret FC presenta su nueva identidad visual.\n\nUna nueva era comienza 🖤\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Rebrand',
      fb: '⭐ TOP SECRET FC · NUEVA IDENTIDAD\n\nEl club presenta oficialmente su nueva imagen visual. Un rediseño que refleja nuestra evolución y el camino que tenemos por delante.\n\nSeguinos en Instagram y X: @fctopsecret\n\n¡Bienvenidos a la nueva era! 🖤⭐\n\n#TopSecretFC #Rebrand #EAFCClubsPro',
    },
  },
  {
    id: 'equipo-temporada-vpn-2026',
    pinned: false,
    category: 'Distinción',
    title: 'Tres jugadores en el Equipo de la Temporada VPN',
    date: '2026-05-04',
    dateLabel: '4 de mayo de 2026',
    excerpt: 'La Liga VPN seleccionó a Lautavester7, cansitrGd22_ y BlackPanther-CG en su equipo ideal de la Temporada 1. Los tres delanteros del club firmaron números históricos.',
    image: 'logos/equipo-temporada-vpn.webp',
    body: [
      'La Liga VPN hizo oficial su Equipo de la Temporada 1 y Top Secret FC tuvo una participación histórica: tres jugadores seleccionados en el once ideal, todos delanteros.',
      'cansitrGd22_ fue el gran protagonista de la temporada con 64 goles y 22 asistencias en 49 partidos, cerrando con un rating promedio de 7.69 — el más alto del club. Sus números lo ubican como uno de los goleadores más letales de toda la liga.',
      'Lautavester7 completó una campaña de lujo con 41 goles y 18 asistencias en 52 partidos. Su versatilidad en el frente de ataque y su rendimiento constante (7.27 de promedio) lo hicieron un fijo en el esquema y merecedor del reconocimiento.',
      'BlackPanther-CG aportó profundidad y desequilibrio con 21 goles y 19 asistencias en 54 partidos — el más activo de los tres. Su capacidad de asociación y los centros al área fueron claves en el juego colectivo del equipo.',
      'El anuncio fue realizado oficialmente por la cuenta de VPN Argentina en X. Top Secret FC es el club con más representantes en el Equipo de la Temporada.',
    ],
    shareCaption: '🏆 ¡EQUIPO DE LA TEMPORADA VPN! 🏆\n\n3 jugadores de Top Secret FC en el XI ideal de la Liga VPN:\n\n⚡ #7 Lautavester7 — 41G · 18A · 7.27 rating\n⚡ #22 cansitrGd22_ — 64G · 22A · 7.69 rating\n⚡ #11 BlackPanther-CG — 21G · 19A · 6.84 rating\n\n🖤⭐ #TopSecretFC #VPN #EquipoDeLaTemporada',
    shareCaptions: {
      ig: '🏆 EQUIPO DE LA TEMPORADA · LIGA VPN\n\n3 de los nuestros en el XI ideal de la Temporada 1 🖤⭐\n\n⚡ Lautavester7 — 41G · 18A\n⚡ cansitrGd22_ — 64G · 22A\n⚡ BlackPanther-CG — 21G · 19A\n\n#TopSecretFC #VPN #EquipoDeLaTemporada #EAFCClubsPro',
      x:  '🏆 3 jugadores de Top Secret FC en el Equipo de la Temporada VPN\n\n⚡ Lautavester7 — 41G · 18A\n⚡ cansitrGd22_ — 64G · 22A\n⚡ BlackPanther-CG — 21G · 19A\n\n#TopSecretFC #VPN #EquipoDeLaTemporada',
      fb: '🏆 ¡EQUIPO DE LA TEMPORADA VPN! 🏆\n\nTop Secret FC tuvo 3 representantes en el once ideal de la Liga VPN Temporada 1. Un reconocimiento histórico para el club.\n\n⚡ Lautavester7 — 41 goles · 18 asistencias\n⚡ cansitrGd22_ — 64 goles · 22 asistencias\n⚡ BlackPanther-CG — 21 goles · 19 asistencias\n\n#TopSecretFC #VPN #EAFCClubsPro',
    },
  },
  {
    id: 'ascenso-primera-2025',
    pinned: true,
    category: 'Histórico',
    title: 'Ascendimos a Primera División',
    date: '2025-05-03',
    dateLabel: '3 de mayo de 2025',
    excerpt: 'Top Secret FC logró el ascenso a la Primera División de la VPN tras una campaña histórica. Un hito que marca el inicio de una nueva era para el club.',
    image: 'logos/Festejo Ascenso.webp',
    body: [
      'Top Secret FC escribió una de las páginas más importantes de su historia al coronarse campeón y obtener el ascenso a la Primera División de la VPN.',
      'Fue una temporada de entrega, trabajo y colectivo. El equipo demostró carácter en los momentos clave y supo imponerse ante rivales de mucho nivel para hacerse merecedor de este logro.',
      'El festejo no tardó en llegar. Los jugadores celebraron el hito con la alegría y la emoción que merece un logro de esta magnitud. Las imágenes del festejo quedaron grabadas en la memoria del club.',
      'A partir de esta temporada, Top Secret FC competirá en la élite del fútbol virtual argentino. El desafío es enorme, pero la base está construida: un plantel comprometido, una identidad clara y una hinchada que acompaña.',
      '¡Arriba Top Secret FC! ¡Primera División!',
    ],
    shareCaption: '🏆 ¡ASCENDIMOS A PRIMERA DIVISIÓN! 🏆\n\nTop Secret FC acaba de lograr uno de los hitos más importantes de su historia. Campaña perfecta, equipo comprometido, resultado histórico.\n\n¡A la Primera División de la VPN! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
    shareCaptions: {
      ig: '🏆 ¡ASCENDIDOS A PRIMERA DIVISIÓN! 🏆\n\nCampaña histórica. Equipo comprometido. Un resultado que quedará para siempre en la memoria del club 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
      x:  '🏆 ¡Top Secret FC asciende a Primera División VPN!\n\nCampaña histórica. Gracias a todos los que acompañaron 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso',
      fb: '🏆 ¡ASCENDIDOS A PRIMERA DIVISIÓN! 🏆\n\nTop Secret FC logró el ascenso a la Primera División de la VPN tras una campaña histórica. Un resultado que quedará para siempre en la historia del club.\n\nGracias a cada jugador, cada entrenamiento y cada partido. Este logro es de todos. ¡Arriba Top Secret FC!\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
    },
  },
];
