// ── TOP SECRET FC · Noticias compartidas ────────────────────────────────────
// Orden: más reciente primero. Agregar nuevas noticias al inicio del array.

const NOTICIAS = [
  {
    id: 'kits-t3-2026',
    pinned: true,
    category: 'Institución',
    title: 'Nueva temporada, nueva marca: Top Secret FC presenta sus kits T3 con Nike',
    date: '2026-06-22',
    dateLabel: '22 de junio de 2026',
    excerpt: 'Top Secret FC presenta su indumentaria para la Temporada 3. Por primera vez con Nike como marca, el club mantiene el negro como identidad y agrega el azul como tercer color — la incorporación más significativa desde la fundación del club.',
    image: 'logos/T3 Kits.png',
    body: [
      'Top Secret FC presenta su indumentaria para la <strong>Temporada 3</strong>. La novedad principal no es solo estética: por primera vez en la historia del club, los kits están <strong>crafted by Nike</strong>. El cambio de marca es una declaración: el club llega a la T3 con estructura, con identidad y con la asociación deportiva más reconocida del mundo respaldando su imagen.',
      '<strong>El kit local — el negro que no se negocia.</strong> La camiseta titular mantiene el negro como color dominante, fiel a la identidad que el club construyó desde su primer partido. Cuello blanco, escudo en el pecho y el sponsoreo de <strong>IFS.ai</strong> como único texto visible sobre la tela. Minimal, directo, Top Secret. La identidad visual del club siempre fue el negro, y la T3 no cambia eso.',
      '<strong>El kit alternativo — el blanco como contraste limpio.</strong> La camiseta alternativa invierte la paleta: blanco dominante con detalles en negro. El mismo sponsor, el mismo escudo, el mismo lenguaje de diseño — solo cambia el fondo. Es la respuesta lógica para las visitas donde el negro del rival genera conflicto. Sin artificio, sin colores accesorios.',
      '<strong>El tercer kit — el azul entra al vestuario.</strong> La incorporación más significativa de esta presentación es el tercer kit. Por primera vez en la historia de Top Secret FC, el <strong>azul royal</strong> forma parte del guardarropa oficial del club. El color no aparece como un detalle decorativo sino como el protagonista total de la camiseta: azul de base, detalles blancos, el mismo sponsor y una identidad nueva pero coherente con el ADN del club. No es un abandono del negro — es una expansión. <em>New Season. Same Identity.</em>',
      'Tres camisetas, una sola dirección. La T3 arranca con la estructura visual más completa que tuvo el club desde su fundación. La pretemporada ya empezó. Los kits también. 🖤⭐',
    ],
    shareCaption: '🖤 NUEVA INDUMENTARIA · TEMPORADA 3 · TOP SECRET FC\n\nPor primera vez con Nike. Tres kits: negro, blanco y el nuevo azul.\n\nNew Season. Same Identity.\n\n#TopSecretFC #NuevosKits #Nike #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 KITS T3 · TOP SECRET FC\n\nPor primera vez con Nike.\n\nNegro · Blanco · Azul — el color que nunca habías visto en Top Secret.\n\nNew Season. Same Identity.\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Nike #EAFCClubsPro',
      x:  '🖤 Top Secret FC presenta sus kits para la Temporada 3.\n\nPrimera vez con Nike. El negro se mantiene. El azul debuta.\n\nNew Season. Same Identity.\n\n#TopSecretFC #NuevosKits',
      fb: '🖤 NUEVA INDUMENTARIA · TEMPORADA 3 · TOP SECRET FC\n\nPor primera vez en la historia del club, los kits están crafted by Nike.\n\n⚫ Kit Local: negro clásico, cuello blanco, IFS.ai\n⚪ Kit Alternativo: blanco con detalles negros\n🔵 Tercer Kit: azul royal — el nuevo color del club\n\nNew Season. Same Identity.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #Nike #EAFCClubsPro',
    },
  },
  {
    id: 'invierno-2026-j1j2',
    pinned: false,
    category: 'Resultado',
    title: 'Campeonato de Invierno: puntaje ideal en el debut — 2-1 y 3-2 en la primera jornada VPUG',
    date: '2026-06-18',
    dateLabel: '18 de junio de 2026',
    excerpt: 'Primera jornada del Campeonato de Invierno VPUG. Dos partidos, dos victorias: 2-1 ante Black Mamba AC y 3-2 ante Vikings Team. Cabers14 y Huber236 lideran con gol y asistencia cada uno. Cinco goleadores distintos en el estreno.',
    image: 'logos/Campeonato Invierno.png',
    body: [
      'Top Secret FC abrió su participación en el <strong>Campeonato de Invierno VPUG</strong> con un debut impecable. La jornada del 18 de junio dejó dos victorias: <strong>2-1 ante Black Mamba AC</strong> en el primer turno y <strong>3-2 ante Vikings Team</strong> en el cierre de la noche. Seis puntos de seis posibles y cinco goleadores distintos en dos partidos.',
      'La distribución del gol es la lectura más importante de esta apertura. No hubo un referente individual que cargara el peso ofensivo: <strong>Agubostero7, Cabers14, Lautavester7, pibu y Huber236</strong> anotaron un gol cada uno. Ciprimancini y BlackPanther sumaron una asistencia cada uno. Un equipo con producción distribuida a lo largo del plantel es más difícil de neutralizar, y estas dos fechas lo confirman desde el primer partido.',
      '<strong>Cabers14 y Huber236 — los más completos de la jornada.</strong> De los siete jugadores de Top Secret con participación directa en la creación de goles, dos sobresalieron por su doble contribución: gol y asistencia en el mismo encuentro. Cabers14 repite el patrón que ya había mostrado en la recta final de la VPUG Temporada 2, donde promedió 7.63 en 14 partidos y cerró con 9.1 ante 4BDOMIFL4NES. Huber236, más presente en los bancos durante la temporada anterior, respondió con eficiencia desde el inicio: presencia en el marcador y en la generación.',
      'El <strong>Campeonato de Invierno VPUG</strong> se disputa martes y jueves, con dos fechas por jornada a las 22:30 y 23:00. El torneo se extiende hasta el 23 de julio, con 21 rondas en total. Top Secret juega en el <strong>Grupo B</strong> y arranca primero en la tabla de posiciones. La próxima jornada es el <strong>martes 23 de junio</strong> — fechas 3 y 4. 🖤⭐',
    ],
    shareCaption: '🖤 CAMPEONATO DE INVIERNO · FECHA 1-2 · TOP SECRET FC\n\nDos victorias · 2-1 vs Black Mamba AC · 3-2 vs Vikings Team\n\nCabers14 y Huber236: 1G+1A · Lautavester7, pibu, Agubostero7: 1G · ciprimancini y BlackPanther: 1A\n\n#TopSecretFC #VPUG #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 INVIERNO 2026 · PRIMERA JORNADA\n\n2-1 vs Black Mamba AC · 3-2 vs Vikings Team\n\n5 goleadores distintos. Cabers14 y Huber236 lideran con 1G+1A cada uno.\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPUG #EAFCClubsPro',
      x:  '🖤 Top Secret FC abre el Campeonato de Invierno VPUG con puntaje ideal.\n\n2-1 vs Black Mamba AC · 3-2 vs Vikings Team\n\n5 goleadores distintos. Grupo B líderes.\n\n#TopSecretFC #VPUG',
      fb: '🖤 CAMPEONATO DE INVIERNO VPUG · FECHA 1 Y 2\n\nTop Secret FC debuta con dos victorias:\n\n⚽ 2-1 vs Black Mamba AC\n⚽ 3-2 vs Vikings Team\n\nGoleadores: Cabers14 (1G+1A), Huber236 (1G+1A), Lautavester7 (1G), pibu (1G), Agubostero7 (1G)\nAsistentes: ciprimancini (1A), BlackPanther (1A)\n\nPróxima fecha: martes 23 de junio.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPUG #EAFCClubsPro',
    },
  },
  {
    id: 'cierre-vpug-t2',
    pinned: false,
    category: 'Análisis',
    title: 'Cierre VPUG T2: 17 partidos, 30 goles y BlackPanther como máximo artillero con 10',
    date: '2026-06-12',
    dateLabel: '12 de junio de 2026',
    excerpt: '17 partidos, 8 victorias, 4 empates y 5 derrotas. 30 goles marcados y 19 recibidos. BlackPanther terminó como goleador de la temporada con 10 tantos. El balance completo de la VPUG T2.',
    image: 'logos/Cierre VPUG T2.png',
    body: [
      'Con los cuatro partidos del 11 de junio, Top Secret FC cerró su participación en la <strong>VPUG Temporada 2</strong>. Diecisiete fechas, 30 goles marcados y un balance de <strong>8 victorias, 4 empates y 5 derrotas</strong>. Una diferencia de goles de +11 que refleja una temporada sólida del primer al último partido.',
      '<strong>BlackPanther — 10 goles, el goleador de la temporada.</strong> El resultado es incontestable: BlackPanther terminó como el máximo artillero de la VPUG T2 con diez tantos. Doblete en el arranque ante United Mito (9.0 de rating), goles ante InfinitX (8.0), dupla goleadora ante Evermeet FC (9.0, 2G+1A), doblete ante Real Marcianos (8.2) y goles ante Germinal, Suda eSports y Nueva Chicago. Una temporada que lo consolida como el delantero más letal del plantel cuando ocupa ese rol.',
      '<strong>Lautavester7 — 9 goles, el otro artillero.</strong> A un gol del líder, Lautavester7 cerró con nueve tantos: doblete ante InfinitX con un 9.3 de rating —el individual más alto de toda la temporada—, dos goles ante Real Marcianos (8.6), y tantos ante United Mito, IACC Cantera, Atletico Moneiro, 4BDOMIFL4NES y Suda eSports. Su 9.3 ante InfinitX es el pico más alto registrado por cualquier jugador del equipo en toda la VPUG T2.',
      '<strong>ciprimancini — el jugador más consistente.</strong> 14 partidos, 7.81 de promedio, el número más alto del plantel. Su mejor noche fue la inaugural: 9.0 ante United Mito con dos asistencias en la goleada 3-0. Presente en todos los partidos importantes, siempre organizado y siempre por encima de 6.9. <strong>Cabers14</strong> promedió 7.63 en 14 partidos y cerró la temporada con su mejor actuación: 9.1 ante 4BDOMIFL4NES con un doblete que definió la victoria 3-2. <strong>J. Martinez</strong> fue el más utilizado: 15 partidos, 7.59 de promedio y el eje de cada partido desde el mediocampo.',
      '<strong>Las dos noches perfectas.</strong> El 28 de mayo y el 1 de junio el equipo mostró su mejor versión con goleadas consecutivas por 4-0. Primero de visita ante Evermeet FC —BlackPanther y lucasmatiakd con doblete cada uno, J. Martinez asistiendo (8.0)—. Después ante Real Marcianos FC con J. Martinez imperial (8.6, 41 pases al 90%), Lautavester7 como referencia ofensiva (8.6, 2G) y BlackPanther sumando gol y asistencia (8.2). Dos partidos sin fisuras que representan el techo colectivo de la temporada.',
      '30 goles marcados, 19 recibidos, +11 en diferencia. BlackPanther y Lautavester7 como dupla goleadora, ciprimancini y J. Martinez como columna vertebral del mediocampo, Cabers14 cerrando desde atrás con consistencia. La base está. La siguiente temporada llega con identidad. 🖤⭐',
    ],
    shareCaption: '🖤 CIERRE VPUG · TEMPORADA 2 · TOP SECRET FC\n\n17 partidos · 8V · 4E · 5D · 30 goles\n\nBlackPanther: 10 goles · Lautavester7: 9 goles · ciprimancini: 7.81 prom · Cabers14: 9.1 vs 4BDOMIFL4NES\n\n#TopSecretFC #VPUG #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 CIERRE VPUG · TEMPORADA 2\n\n17 partidos. Balance final:\n\n8V · 4E · 5D · 30 goles\n\nBlackPanther: 10G · Lautavester7: 9G · ciprimancini: 7.81 prom\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPUG #EAFCClubsPro',
      x:  '🖤 Top Secret FC cierra la VPUG T2.\n\n8V-4E-5D · 30 goles marcados · +11 diferencia\n\nBlackPanther: 10 goles. Lautavester7: 9. ciprimancini: 7.81 prom.\n\n#TopSecretFC #VPUG',
      fb: '🖤 CIERRE VPUG · TEMPORADA 2 · TOP SECRET FC\n\n17 partidos. Balance final:\n\n📊 8 victorias · 4 empates · 5 derrotas\n📊 30 goles marcados · 19 recibidos · diferencia +11\n\nBlackPanther: 10 goles (máximo artillero). Lautavester7: 9 goles. lucasmatiakd: 4. ciprimancini: 7.81 promedio en 14 partidos. J. Martinez: 7.59 en 15 partidos. Cabers14: 9.1 ante 4BDOMIFL4NES en el cierre.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPUG #EAFCClubsPro',
    },
  },
  {
    id: 'cierre-11x11-t2',
    pinned: false,
    category: 'Análisis',
    title: 'Cierre 11x11 T2: equilibrio en el marcador, Lautavester7 y lucasmatiakd mandan arriba',
    date: '2026-06-09',
    dateLabel: '9 de junio de 2026',
    excerpt: '9 partidos, 4 victorias, 14 goles. La liga más equilibrada de la temporada cerró con balance positivo. Lautavester7 y lucasmatiakd terminaron como cogoleadores con 5 tantos cada uno. ciprimancini fue el jugador más consistente del torneo.',
    image: 'logos/Cierre 11x11 T2.png',
    body: [
      'Con nueve partidos disputados entre el 19 de mayo y el 28 de mayo de 2026, Top Secret FC cerró su participación en el <strong>11x11 Temporada 2</strong>. El balance final fue de <strong>4 victorias, 1 empate y 4 derrotas</strong>, con 14 goles marcados y 12 recibidos. Una campaña pareja, con picos ofensivos notables y un colectivo que encontró su mejor versión en los partidos más importantes.',
      'El equipo arrancó con dos derrotas en la primera jornada —1-2 ante Los Waxiturros y 1-2 de visita ante Argentino de Merlo— pero se recompuso de inmediato con victorias consecutivas por 1-0 ante Ferro eSp y Dep Ballester. Luego llegó el empate ante All Boys, la caída ante Comunicaciones, otra derrota ante IACC Reserva, y el cierre más explosivo de la temporada: <strong>victoria 4-2 ante 4BDOMIFL4NES y 2-0 ante Los Picantes eSports</strong> en los dos últimos partidos. El equipo terminó ganando cuando más importaba.',
      '<strong>Lautavester7 y lucasmatiakd — 5 goles cada uno.</strong> Dos atacantes, igual cosecha. Lautavester7 fue el más espectacular: doblete en F8 ante 4BDOMIFL4NES con 9.2 de rating —el más alto del torneo—, goles en F1, F2 y F4, y dos asistencias adicionales. lucasmatiakd respondió con peso propio: dos goles en F8 (8.5 de rating) más tantos en F5, F6 y F9 para cerrar con el mismo total. Juntos generaron el 71% de los goles del equipo en el torneo.',
      '<strong>ciprimancini — el más consistente.</strong> Sin goleadas individuales durante casi todo el campeonato, el mediocampista fue el jugador que más sostuvo el nivel partido a partido. Su promedio de rating fue el más alto del plantel, con valores que oscilaron entre 6.9 y 9.2. Cerró la competencia con su mejor actuación: el partido ante Los Picantes eSports donde fue figura con 9.2, un gol y una asistencia. Un rendimiento que confirma su rol como motor creativo del equipo.',
      '<strong>AR ELTIO — el mejor de la defensa.</strong> El defensor central acumuló los ratings defensivos más altos de toda la campaña. Su actuación ante IACC Reserva (8.9) fue la mejor individual de cualquier jugador en un partido sin victoria. Presente en los nueve encuentros, su consistencia fue el pilar de la línea de fondo. <strong>Pibu</strong> sumó desde el lateral con dos asistencias clave y promedios que lo ubicaron entre los mejores de la campaña. <strong>J. Martinez</strong> completó los nueve partidos con 7.5 de promedio, dos asistencias y el rol de organizador desde el mediocampo.',
      'El 11x11 fue el frente más equilibrado de la Temporada 2. El potencial ofensivo estuvo siempre presente; la próxima temporada, la consistencia defensiva será el factor que incline la balanza. 🖤⭐',
    ],
    shareCaption: '🖤 CIERRE 11x11 · TEMPORADA 2 · TOP SECRET FC\n\n9 partidos · 4V · 1E · 4D · 14 goles\n\nLautavester7: 5G · lucasmatiakd: 5G · ciprimancini: 7.73 promedio · AR ELTIO: 8.9 ante IACC\n\n#TopSecretFC #11x11 #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 CIERRE 11x11 · TEMPORADA 2\n\n9 partidos. 4-1-4. 14 goles marcados.\n\nLautavester7: 5G · lucasmatiakd: 5G · ciprimancini: mejor promedio del torneo\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #11x11 #EAFCClubsPro',
      x:  '🖤 Top Secret FC cierra el 11x11 T2.\n\n4V-1E-4D · 14 goles marcados\n\nLautavester7 y lucasmatiakd: 5 goles cada uno. ciprimancini: mejor promedio.\n\n#TopSecretFC #11x11',
      fb: '🖤 CIERRE 11x11 · TEMPORADA 2 · TOP SECRET FC\n\n9 partidos disputados. Balance final:\n\n📊 4 victorias · 1 empate · 4 derrotas\n📊 14 goles marcados · 12 recibidos\n\nLautavester7 y lucasmatiakd: 5 goles cada uno (71% del total). ciprimancini: el jugador más consistente del torneo con 9.2 ante Los Picantes en el cierre. AR ELTIO: 8.9 ante IACC Reserva.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #11x11 #EAFCClubsPro',
    },
  },
  {
    id: 'cierre-vpn-t2',
    pinned: true,
    category: 'Análisis',
    title: 'Cierre VPN T2: 19 partidos en Primera División, Lautavester7 termina con 13 goles',
    date: '2026-06-09',
    dateLabel: '9 de junio de 2026',
    excerpt: '19 partidos en la Primera División de la VPN. El salto de categoría fue exigente: 1 victoria, 2 empates y 16 derrotas. Pero Lautavester7 convirtió 13 goles para liderar la tabla de artilleros. Un cierre agridulce con lecciones para la próxima temporada.',
    image: 'logos/Cierre VPN T2.png',
    body: [
      'Con el partido ante Belgrano Esports del 8 de junio, Top Secret FC cerró su primera temporada completa en la <strong>Primera División de la VPN</strong>. Diecinueve partidos, 23 goles marcados y un registro de <strong>1 victoria, 2 empates y 16 derrotas</strong>. El salto desde la categoría anterior a la élite fue directo y el nivel del torneo lo hizo notar partido a partido. Sin embargo, en ese contexto, los números individuales de algunos jugadores tienen aún más valor.',
      '<strong>El escenario.</strong> La VPN de Primera División es el torneo más competitivo de los tres en que participa el club. En casi todos los encuentros el equipo mantuvo la posesión —57% de promedio a lo largo de la temporada— y generó situaciones, pero la efectividad ofensiva y la solidez defensiva no estuvieron siempre alineadas. Los dos empates (ante Riestra eSports y Monoidales) y la única victoria (3-1 ante Belgrano Esports en el cierre) muestran que cuando el equipo funcionó en bloque, el resultado llegó.',
      '<strong>Lautavester7 — 13 goles, el artillero de la temporada.</strong> Sin discusión. El delantero anotó en 11 de los 18 partidos que disputó, terminó con trece tantos y fue el jugador más determinante en ataque. Su temporada incluyó un doblete ante Belgrano Esports en el cierre (8.1 de rating), goles ante Escuela Vieja, Real Black FC, San Jorge, CAI Esports, San Lorenzo, y más. En los partidos donde convirtió, el equipo respondió colectivamente. Su presencia en el área fue el recurso ofensivo principal de la temporada.',
      '<strong>ciprimancini y J. Martinez — el motor del mediocampo.</strong> Ambos jugaron los 19 partidos. J. Martinez acumuló un promedio de 7.31 de rating con valores siempre por encima de 7 salvo en los momentos más difíciles —F11, F18—, completó entre 16 y 41 pases por partido y fue el eje de la distribución de todos los encuentros. Su mejor actuación fue ante Monoidales (8.2, 41 pases al 88%) donde el equipo rescató el empate. ciprimancini promedió 7.23, con su pico más alto ante Nueva Chicago eSports (8.9) y una consistencia que lo posicionó como el mediocampista más regular de la temporada. Dos asistencias y cero goles son un reflejo honesto de su rol: organizar, no rematar.',
      '<strong>Cabers14 — el más sólido de la defensa.</strong> Presente en 16 de 19 partidos, el defensor central promedió 7.33 de rating y fue la constante más fiable en la línea de fondo. Su mejor partido fue ante CAI Esports (8.0), pero su valor está más en la regularidad que en los picos. <strong>Agubostero7</strong> llegó a la mitad de la temporada y aportó desde el primer partido: 8.4 ante Instituto Esports en su debut es el rating defensivo más alto de toda la campaña en la liga. <strong>Guiidow</strong> tuvo destellos notables —8.3 ante Aesma, 8.1 ante Chacarita— como el mejor lateral ofensivo en los momentos de mayor exigencia.',
      'La VPN T2 fue una escuela. El equipo demostró que puede jugar con la pelota en las instancias más competitivas del fútbol virtual argentino. La siguiente temporada llega con más rodaje y con Lautavester7 como referencia comprobada en Primera División. 🖤⭐',
    ],
    shareCaption: '🖤 CIERRE VPN · TEMPORADA 2 · TOP SECRET FC\n\n19 partidos en Primera División · 1V · 2E · 16D · 23 goles\n\nLautavester7: 13 goles · J. Martinez: 7.31 promedio · ciprimancini: 19 partidos · Cabers14: 7.33 prom. defensa\n\n#TopSecretFC #VPN #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 CIERRE VPN · TEMPORADA 2\n\n19 partidos en Primera División.\n\nLautavester7: 13G · J. Martinez: 7.31 prom · ciprimancini: 19 partidos al nivel\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #EAFCClubsPro',
      x:  '🖤 Top Secret FC cierra la VPN T2 en Primera División.\n\n1V-2E-16D · 23 goles marcados\n\nLautavester7: 13 goles. J. Martinez y ciprimancini: los 19 partidos.\n\n#TopSecretFC #VPN',
      fb: '🖤 CIERRE VPN · TEMPORADA 2 · TOP SECRET FC\n\n19 partidos en la élite de la VPN. Balance final:\n\n📊 1 victoria · 2 empates · 16 derrotas\n📊 23 goles marcados · posesión promedio: 57%\n\nLautavester7: 13 goles (artillero de la temporada). J. Martinez y ciprimancini: los únicos dos jugadores presentes en los 19 encuentros, ambos con promedio por encima de 7.2. Cabers14: 7.33 promedio defensivo en 16 partidos. Agubostero7: 8.4 en su debut ante Instituto.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPN #EAFCClubsPro',
    },
  },
  {
    id: 'destacados-semana3-t2',
    pinned: false,
    category: 'Destacados',
    title: 'Semana 3: la goleada en VPUG y el punto arrancado en VPN',
    date: '2026-06-05',
    dateLabel: '5 de junio de 2026',
    excerpt: '9 partidos en 4 noches. La VPN rescató un empate ante Monoidales tras cuatro derrotas. La VPUG brilló con un 4-0 a Real Marcianos. Sin actividad en el 11x11. Lautavester7 convirtió 5 goles en la semana.',
    image: 'logos/Destacados Sem3.png',
    body: [
      'Entre el 1 y el 4 de junio, Top Secret FC afrontó nueve partidos repartidos en la VPN y la VPUG. <strong>Sin actividad en el 11x11</strong>, la semana se concentró en los dos frentes más exigentes de la temporada y dejó una lectura clara: una victoria dominante, tres empates peleados y cinco derrotas que no desdibujan lo que el equipo viene construyendo.',
      '<strong>VPN — Cinco partidos, un punto vital.</strong> El lunes fue la jornada más dura: tres partidos en una sola noche y tres derrotas. Ante Instituto Esports (1-3 de visita) Agubostero7 descontó y fue figura con 8.4 de rating; Alexisraies2 (8.9) fue el más sólido de la zaga y el número individual más alto de toda la semana. En el segundo partido, la caída 1-2 ante Estudiantes LP de local fue un duelo de dominio sin recompensa —58% de posesión, 3 tiros— con Lautavester7 marcando el descuento y Alexisraies2 (8.3) y J. Martinez (7.9) como los mejores. La noche cerró con la derrota más abultada: 1-5 de visita ante Talleres eSports, aunque el equipo generó —7 tiros, 1.8 xG— y Guiidow (7.9) y Agubostero7 (7.8) se mantuvieron al nivel. El miércoles trajo dos partidos de signo distinto: primero la frustración de caer 0-1 ante FCO Cannabiense con 61% de posesión y 4 tiros sin convertir, y después la mejor noticia de la VPN en la semana: empate 1-1 de visita ante Monoidales con J. Martinez en modo excepcional (8.2, 41 pases, 88% de precisión), ciprimancini dominando el mediocampo (8.0) y lucasmatiakd anotando el gol. Pibu sumó asistencia. El equipo manejó el 62% de la posesión y generó 9 tiros. Un punto rescatado que sabe bien.',
      '<strong>VPUG — Del 4-0 a la resiliencia.</strong> La jornada más brillante de toda la semana llegó el mismo lunes: 4-0 de visita ante Real Marcianos FC. Lautavester7 (8.6) anotó dos veces, BlackPanther (8.2) sumó gol y asistencia, lucasmatiakd convirtió el cuarto tanto (7.8) y J. Martinez (8.6) fue el arquitecto desde el mediocampo con 41 pases al 90% de precisión. ciprimancini (8.4) y Agubostero7 (7.8) completaron una noche sin fisuras. El martes llegó el tropiezo: derrota 0-2 ante Team Valhalla de local con 60% de posesión pero apenas 4 tiros y 0.6 xG. Cabers14 (8.5) fue la figura individual en la derrota. El miércoles el equipo respondió con el mejor partido colectivo de la VPUG en la semana: empate 2-2 de visita ante Germinal eSports, con J. Martinez otra vez imperial (8.3, 30 pases, 90% de precisión), R.RS32DaniSton brillando con 8.4 y Cabers14 sólido (8.0); lucasmatiakd y BlackPanther anotaron. El jueves cerró con un empate 1-1 ante Atlético Moneiro de local: Lautavester7 abrió el marcador, lucasmatiakd asistió y J. Martinez (8.0) fue el mejor de la cancha.',
      'En el plano individual, <strong>Alexisraies2</strong> firmó el rating más alto de la semana con 8.9 ante Instituto Esports —una actuación defensiva completa que marcó el tono del bloque de fondo—. <strong>J. Martinez</strong> fue el jugador de la semana sin discusión: nueve partidos completados, promedios de pases altísimos (41 al 90% ante Real Marcianos, 30 al 90% ante Germinal, 41 al 88% ante Monoidales) y ratings entre 7.2 y 8.6 en toda la semana. <strong>Lautavester7</strong> fue el máximo goleador con cinco tantos y su 8.6 ante Real Marcianos como cima. <strong>Cabers14</strong> tuvo la mejor semana de su temporada en la VPUG: 8.5 ante Valhalla y 8.0 ante Germinal como picos. <strong>R.RS32DaniSton</strong> brilló con 8.4 ante Germinal en su mejor actuación de la temporada.',
      'Nueve partidos. Once goles. Una semana de contrastes entre el mejor resultado de la temporada en la VPUG y el desafío que sigue pendiente en la VPN. El 11x11 retoma esta semana. 🖤⭐',
    ],
    shareCaption: '🖤 SEMANA 3 · TEMPORADA 2 · TOP SECRET FC\n\n9 partidos · 2 ligas · 4 noches\n\nVPN: 0V · 1E · 4D — empate rescatado ante Monoidales\nVPUG: 1V · 2E · 1D — goleada 4-0 ante Real Marcianos\n11x11: sin actividad\n\nLautavester7: 5 goles · Alexisraies2: 8.9 rating · J. Martinez: 9 partidos al máximo nivel\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 SEMANA 3 · TEMPORADA 2\n\n9 partidos. Dos ligas. Balance:\n\nVPN 0-1-4 · VPUG 1-2-1\n\nLautavester7: 5G · Alexisraies2: 8.9 · J. Martinez: 9 partidos al máximo nivel\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #VPUG #EAFCClubsPro',
      x:  '🖤 Semana 3 de Temporada 2 completada.\n\nVPN 0-1-4 · VPUG 1-2-1\n\n9 partidos en 4 noches. 4-0 a Real Marcianos. Lautavester7: 5 goles.\n\n#TopSecretFC #VPN #VPUG',
      fb: '🖤 SEMANA 3 · TEMPORADA 2 · TOP SECRET FC\n\nBalance de la tercera semana:\n\n📊 VPN: 0 victorias · 1 empate · 4 derrotas — punto rescatado vs Monoidales en el cierre\n📊 VPUG: 1 victoria · 2 empates · 1 derrota — goleada 4-0 ante Real Marcianos\n📊 11x11: sin actividad\n\nLautavester7: 5 goles en la semana. Alexisraies2: 8.9 rating ante Instituto (máximo de la semana). J. Martinez completó los 9 partidos con rating siempre por encima de 7.2.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPN #VPUG #EAFCClubsPro',
    },
  },
  {
    id: 'destacados-semana2-t2',
    pinned: false,
    category: 'Destacados',
    title: 'Semana 2: el jueves salva la semana',
    date: '2026-05-29',
    dateLabel: '29 de mayo de 2026',
    excerpt: '11 partidos en 3 noches. La VPN sigue sin ceder puntos. El VPUG cerró con una goleada. El 11x11 respondió con dos victorias seguidas. lucasmatiakd convirtió 8 goles en la semana.',
    image: 'logos/Destacados Sem2.png',
    body: [
      'Entre el 26 y el 28 de mayo, Top Secret FC completó su segunda semana de competencia en la Temporada 2. <strong>11 partidos en tres noches</strong>, distribuidos en las tres ligas. La semana fue de contrastes: un miércoles para olvidar en los tres frentes, y un jueves de respuesta colectiva donde el equipo convirtió 10 goles en tres partidos.',
      '<strong>VPN — El nudo que no afloja.</strong> Tres partidos, tres derrotas, tres goles marcados y siete recibidos. El miércoles fue el día más exigente en la Primera División: ante Aesma Gaming (0-1 de visita) el equipo propuso, tuvo el 54% de posesión y generó por los costados, pero con apenas 2 tiros y 0.4 de xG el gol propio nunca llegó. Guiidow fue la figura con 8.3. Ante CAI Esports (2-3 de local) el nivel ofensivo apareció — Lautavester7 y lucasmatiakd anotaron, Buraa 07 (7.6) distribuyó desde el mediocampo — pero la solidez defensiva siguió siendo el problema. San Lorenzo Esports cerró la noche con un 3-1 donde Lautavester7 anotó el descuento y J. Martinez (7.7) fue el mejor del plantel. La VPN no perdona errores defensivos y el equipo todavía no encontró el equilibrio entre ataque y retaguardia.',
      '<strong>VPUG — Del bache al golazo.</strong> La semana en la VPUG arrancó mal: derrota 1-2 de visita ante I.A.C.C Cantera el martes — Lautavester7 descontó con asistencia de Cabers14 — y caída en casa 0-1 ante Hacha eSports el miércoles. Pero el jueves llegó la respuesta más contundente de toda la semana: 4-0 de visita ante Evermeet FC. BlackPanther fue la figura del partido con 9.0 (2 goles y asistencia), lucasmatiakd sumó otros dos tantos con 8.6 de rating y J. Martinez (8.0) organizó desde el mediocampo con 34 pases y una asistencia. Una noche perfecta en el momento justo.',
      '<strong>11x11 — Reacción en el cierre.</strong> El martes fue parejo pero sin premio: 1-1 ante All Boys con gol de lucasmatiakd y asistencia de Pibu, y luego derrota 2-3 ante Comunicaciones eSports donde el equipo llegó con claridad (lucasmatiakd y Huber236 anotaron, J. Martinez asistió) pero no sostuvo el resultado. El jueves fue otra historia. La primera salida terminó en derrota 1-2 ante IACC Reserva, pero el equipo respondió de inmediato: victoria 4-2 ante 4BDOMIFL4NES con Lautavester7 en modo estelar (9.2, 2 goles y asistencia) y lucasmatiakd imparable (8.5, 2 goles más). Para cerrar, 2-0 ante Los Picantes eSports: ciprimancini como figura total (9.2, 1 gol y asistencia), Pibu sumando otra asistencia y el equipo dominando con 65% de posesión.',
      'En el plano individual, <strong>lucasmatiakd</strong> fue el jugador de la semana con 8 goles en siete partidos — cuatro solo en el miércoles, con doblete ante 4BDOMIFL4NES y doblete ante Evermeet FC. <strong>Lautavester7</strong> anotó cinco veces (Cantera, CAI, San Lorenzo y dos ante los 4B) y su 9.2 ante 4BDOMIFL4NES fue el rating individual más alto del período. <strong>BlackPanther</strong> protagonizó la mejor actuación colectiva con 9.0 y un partido completo ante Evermeet (2G+1A). <strong>ciprimancini</strong> cerró la semana de 11x11 con 9.2 y participación directa en los dos goles ante Los Picantes. En defensa, <strong>AR ELTIO</strong> fue el mejor de la línea con 8.9 ante IACC Reserva. <strong>J. Martinez</strong> completó los 11 partidos acumulando 8.1 ante IACC Reserva y 8.0 ante Evermeet como mejores actuaciones de la semana.',
      'Semana 2 completada. El desafío en la VPN sigue pendiente; el VPUG y el 11x11 muestran que el potencial está. 🖤⭐',
    ],
    shareCaption: '🖤 SEMANA 2 · TEMPORADA 2 · TOP SECRET FC\n\n11 partidos · 3 ligas · 3 noches\n\nVPN: 0V · 0E · 3D — el desafío persiste\nVPUG: 1V · 0E · 2D — goleada ante Evermeet (4-0)\n11x11: 2V · 1E · 2D — dos victorias en el cierre\n\nlucasmatiakd: 8 goles · Lautavester7: 5 goles · BlackPanther: 9.0 vs Evermeet\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 SEMANA 2 · TEMPORADA 2\n\n11 partidos. Tres ligas. Balance real:\n\nVPN 0-0-3 · VPUG 1-0-2 · 11x11 2-1-2\n\nlucasmatiakd: 8G · Lautavester7: 5G · BlackPanther: 9.0 ante Evermeet\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
      x:  '🖤 Semana 2 de Temporada 2 completada.\n\nVPN 0-0-3 · VPUG 1-0-2 · 11x11 2-1-2\n\n11 partidos en 3 noches. lucasmatiakd: 8 goles en la semana.\n\n#TopSecretFC #VPN #VPUG #11x11',
      fb: '🖤 SEMANA 2 · TEMPORADA 2 · TOP SECRET FC\n\nBalance de la segunda semana en tres competencias:\n\n📊 VPN: 0 victorias · 0 empates · 3 derrotas — el frente más duro de la temporada\n📊 VPUG: 1 victoria · 0 empates · 2 derrotas — cierre goleador (4-0 ante Evermeet)\n📊 11x11: 2 victorias · 1 empate · 2 derrotas — dos victorias seguidas el miércoles\n\nlucasmatiakd convirtió 8 goles en la semana. Lautavester7: 5 goles. BlackPanther: 9.0 ante Evermeet (2G+1A). ciprimancini: 9.2 ante Los Picantes.\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    },
  },
  {
    id: 'destacados-semana1-t2',
    pinned: false,
    category: 'Destacados',
    title: 'Semana 1 de Temporada 2: análisis de los tres frentes',
    date: '2026-05-22',
    dateLabel: '22 de mayo de 2026',
    excerpt: '17 partidos en 9 días. Arranque duro en la VPN, sólido en VPUG, y en 11x11 dos caídas seguidas antes de cerrar el miércoles con dos victorias en fila. Un repaso por el rendimiento colectivo de la primera semana de la nueva era.',
    image: 'logos/Destacados Sem1.png',
    body: [
      'Entre el 13 y el 21 de mayo, Top Secret FC completó su primera semana de competencia en la Temporada 2. <strong>17 partidos en 9 días</strong>, repartidos en tres ligas con exigencias distintas y resultados muy diferentes entre sí.',
      '<strong>VPN — El golpe de realidad.</strong> Nueve partidos, cero victorias, un empate y ocho derrotas. El salto a Primera División es exigente y los números lo confirman: en la mayoría de los encuentros el equipo mantuvo la pelota (entre el 53% y el 70% de posesión) y llegó con volumen al área, pero la efectividad no acompañó y la solidez defensiva fue irregular. El único punto llegó en el cierre de la tercera jornada, un empate 1-1 ante Riestra eSports con gol de BlackPanther. La VPN es el desafío pendiente de la temporada.',
      '<strong>VPUG — El mejor frente de la semana.</strong> Cuatro partidos, tres victorias. La semana arrancó con una goleada 3-0 de visitante ante United Mito —70% de posesión, precisión perfecta en los tiros— y siguió con un triunfo 2-0 ante Olimpo eSports, donde Alexisraies2 convirtió los dos tantos. La única caída fue ante All Boys (1-2) en casa, aunque el equipo respondió de inmediato con la victoria más emotiva de la semana: la remontada 3-2 sobre InfinitX el miércoles, con Lautavester7 anotando el gol del empate y la victoria. ciprimancini fue la figura de la jornada inaugural con 9.0 de rating.',
      '<strong>11x11 — Reacción a tiempo.</strong> Cuatro partidos, dos victorias y dos derrotas. El lunes fue el día más difícil: caída 1-2 ante Los Waxiturros de local y derrota 1-2 de visitante ante Argentino de Merlo en el mismo día. Sin embargo, el equipo se recompuso con creces el miércoles: dos victorias consecutivas por 1-0, primero ante Ferro eSp y luego ante Dep. Ballester, con Buraa 07 (7.8 de rating) y AR ELTIO (8.4, Futbolista del Partido) como figuras respectivas. 21 entradas completadas ante Ferro y portería en cero en ambos encuentros del cierre.',
      'En el plano individual, <strong>Lautavester7</strong> cerró la semana con 12 goles entre las tres ligas y es la referencia ofensiva del plantel. <strong>BlackPanther</strong> anotó en VPN, VPUG y 11x11 —8 goles en total— siendo el único jugador con presencia en el marcador de los tres torneos. <strong>J. Martinez</strong> disputó los 17 partidos, acumulando hasta 19.8 km recorridos en una sola noche, y mantuvo rating por encima de 7 en prácticamente todos los encuentros.',
      'Semana 1 completada. La Temporada 2 tiene forma. 🖤⭐',
    ],
    shareCaption: '🖤 SEMANA 1 · TEMPORADA 2 · TOP SECRET FC\n\n17 partidos · 3 ligas · 9 días\n\nVPN: 0V · 1E · 8D — arranque duro en la élite\nVPUG: 3V · 0E · 1D — sólidos\n11x11: 2V · 0E · 2D — reacción a tiempo\n\nLautavester7: 12 goles · BlackPanther: 8 goles en 3 ligas\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 SEMANA 1 · TEMPORADA 2\n\n17 partidos. Tres ligas. Un balance real:\n\nVPN 0-1-8 · VPUG 3-0-1 · 11x11 2-0-2\n\nLautavester7: 12G · BlackPanther: 8G en las 3 ligas · ciprimancini: 9.0 rating\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
      x:  '🖤 Semana 1 de Temporada 2 completada.\n\nVPN 0-1-8 · VPUG 3-0-1 · 11x11 2-0-2\n\n17 partidos en 9 días. La nueva era arrancó.\n\n#TopSecretFC #VPN #VPUG #11x11',
      fb: '🖤 SEMANA 1 · TEMPORADA 2 · TOP SECRET FC\n\nBalance de la primera semana en tres competencias:\n\n📊 VPN: 0 victorias · 1 empate · 8 derrotas — arranque duro en Primera División\n📊 VPUG: 3 victorias · 0 empates · 1 derrota — sólidos\n📊 11x11: 2 victorias · 0 empates · 2 derrotas — reacción a tiempo\n\nLautavester7 cerró la semana con 12 goles entre las tres ligas. BlackPanther anotó en los tres torneos (8 goles en total). J. Martinez jugó los 17 partidos.\n\nLa Temporada 2 tiene forma. 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #VPN #VPUG #11x11 #EAFCClubsPro',
    },
  },
  {
    id: 'nuevo-ct-2026',
    pinned: false,
    category: 'Institucional',
    title: 'Top Secret FC presenta su nuevo Cuerpo Técnico',
    date: '2026-05-15',
    dateLabel: '15 de mayo de 2026',
    excerpt: 'Top Secret FC anuncia la conformación oficial de su nuevo Cuerpo Técnico. Cinco nombres, cinco roles, una sola dirección: llevar al club a lo más alto de la Primera División.',
    image: 'logos/Nuevo CT.png',
    body: [
      'Top Secret FC hace oficial la conformación de su nuevo Cuerpo Técnico de cara a la Temporada 2. Cinco integrantes, roles bien definidos y una convicción compartida: este club tiene todo para competirle a cualquiera en la élite del fútbol virtual argentino.',
      '<strong>#6 · Juan_Martinez4 — Director Técnico.</strong> El cerebro del equipo asume la conducción táctica. Define sistemas, gestiona el plantel y toma las decisiones que marcan el rumbo de cada partido. La pelota en el centro de la mesa no es casual.',
      '<strong>#32 · CipriMancini — Analista Táctico.</strong> El encargado de estudiar a los rivales antes de cada fecha. Lectura del juego, informes de video y propuestas para neutralizar al oponente. La preparación empieza antes de conectarse.',
      '<strong>#20 · Guiidow — Preparador Físico y Rendimiento.</strong> Gestiona la rotación del plantel, el estado de forma de cada jugador y los tiempos de carga y descanso durante la temporada. La base de un equipo competitivo es llegar siempre al cien.',
      '<strong>#7 · Lautavester7 — Entrenador de Línea Ofensiva.</strong> Especialista en patrones de ataque, combinaciones y pressing alto. Su experiencia como uno de los delanteros más letales del club convierte su mirada en un recurso invaluable para la línea de ataque.',
      '<strong>#30 · zPibu__ — Coordinador de Plantel y Mercado.</strong> Maneja la comunicación interna del grupo, la disponibilidad de jugadores para cada convocatoria y el seguimiento del mercado. El vínculo entre lo que pasa adentro y lo que se proyecta hacia afuera.',
      'Cinco roles distintos, mismo objetivo. El Cuerpo Técnico de Top Secret FC ya está trabajando. 🖤⭐',
    ],
    shareCaption: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nPresentamos oficialmente al CT que conducirá al club en la Temporada 2:\n\n📋 DT: Juan_Martinez4\n🔍 Analista: CipriMancini\n💪 Físico: Guiidow\n⚡ Ataque: Lautavester7\n🗂️ Coordinador: zPibu__\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
    shareCaptions: {
      ig: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nPresentamos oficialmente al CT que conducirá al club en la Temporada 2.\n\n📋 DT: Juan_Martinez4 · Analista: CipriMancini · Físico: Guiidow · Ataque: Lautavester7 · Coordinador: zPibu__\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
      x:  '🖤 Top Secret FC presenta su nuevo Cuerpo Técnico para la Temporada 2.\n\nDT: Juan_Martinez4 · Analista: CipriMancini · Físico: Guiidow · Ataque: Lautavester7 · Coordinador: zPibu__\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
      fb: '🖤 NUEVO CUERPO TÉCNICO · TOP SECRET FC ⭐\n\nEl club presenta oficialmente al Cuerpo Técnico que conducirá al equipo en la Temporada 2. Cinco integrantes, roles bien definidos, mismo objetivo.\n\n📋 DT: Juan_Martinez4\n🔍 Analista Táctico: CipriMancini\n💪 Preparador Físico: Guiidow\n⚡ Entrenador de Ataque: Lautavester7\n🗂️ Coordinador de Plantel: zPibu__\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
    },
  },
  {
    id: 'fixture-vpn-t2-2026',
    pinned: false,
    category: 'Fixture',
    title: 'Ya tenemos fixture: 19 partidos en la Primera División VPN',
    date: '2026-05-13',
    dateLabel: '13 de mayo de 2026',
    excerpt: 'La Liga VPN publicó el calendario oficial de la Temporada 2. Top Secret FC jugará 19 partidos en su debut en Primera División, con el primer partido hoy mismo.',
    image: 'logos/Fixture VPN.webp',
    body: [
      'Ya está oficial. La Liga VPN publicó el calendario completo de la Temporada 2 y Top Secret FC tiene por delante 19 partidos en su primera experiencia en la élite del fútbol virtual argentino.',
      'El debut es hoy: tres encuentros en una misma jornada frente a <strong>Escuela Vieja</strong> (Local · 23:00), <strong>Nueva Chicago eSports</strong> (Visita · 23:30) y <strong>Real Black</strong> (Local · 23:59). Un arranque exigente que marcará el tono de lo que viene.',
      'El fixture se extiende hasta el <strong>8 de junio</strong> con rivales de primer nivel: Comunicaciones, San Lorenzo Esports, Instituto Esports, Estudiantes LP, Talleres Esports, Belgrano Esports y más. Diecinueve jornadas que pondrán a prueba el nivel del plantel en la categoría más competitiva de la VPN Argentina.',
      'El desafío es histórico. Es la primera vez que Top Secret FC compite en Primera División y el club llega con un plantel renovado, hambre de demostrar y la convicción de que puede competirle a cualquiera.',
      'El fixture completo está disponible en el calendario del sitio. Confirmá tu asistencia para cada partido y seguí de cerca cada resultado. 🖤⭐',
    ],
    shareCaption: '📋 FIXTURE OFICIAL · TEMPORADA 2\n\nTop Secret FC ya tiene calendario en la Primera División VPN:\n\n🗓️ 19 partidos\n📅 13 mayo → 8 junio\n🏆 VPN Argentina · Primera División\n\nEl debut es HOY. ¡Vamos! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision',
    shareCaptions: {
      ig: '📋 FIXTURE OFICIAL · TEMPORADA 2 🖤\n\n19 partidos. 7 fechas. Primera División VPN.\n\nEl debut es HOY ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #PrimeraDivision #EAFCClubsPro #Fixture',
      x:  '📋 Ya tenemos fixture en Primera División VPN.\n\n19 partidos entre el 13/05 y el 08/06.\n\nEl debut es hoy 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #VPN #PrimeraDivision',
      fb: '📋 FIXTURE OFICIAL · TEMPORADA 2\n\nLa Liga VPN publicó el calendario completo y Top Secret FC tiene 19 partidos por delante en su debut en Primera División.\n\n🗓️ 13 de mayo al 8 de junio\n🏆 VPN Argentina · Primera División\n\nEl primer partido es hoy. ¡Vamos Top Secret FC! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #EAFCClubsPro',
    },
  },
  {
    id: 'plantel-2026',
    pinned: false,
    category: 'Plantel',
    title: 'Este es el plantel que jugará la nueva temporada',
    date: '2026-05-11',
    dateLabel: '11 de mayo de 2026',
    excerpt: 'Top Secret FC presenta oficialmente el plantel para la temporada 2026. Dieciséis jugadores, una misma misión: competir en la élite del fútbol virtual argentino.',
    image: 'logos/Plantel T2 2026.webp',
    body: [
      'Top Secret FC presenta el plantel que defenderá los colores del club en la temporada 2026. Dieciséis jugadores comprometidos con el proyecto, con historia dentro de la institución y con hambre de seguir creciendo.',
      'El bloque viene reforzado. A la base que logró el ascenso se suman tres incorporaciones que elevan la competencia interna y dan mayor profundidad en todas las líneas. El desafío es enorme — Primera División de la VPN — y el plantel está a la altura.',
      'En el arco, <strong>pauloco10 (#19)</strong> y <strong>Woolfyboyzx2 (#45)</strong> se disputan el puesto de titular. Atrás, <strong>Alexisraies23 (#3)</strong>, <strong>Cabers14 (#4)</strong>, <strong>AR-ELTIO (#21)</strong> y <strong>Agubostero7 (#31)</strong> forman una defensa sólida, mientras que <strong>Huber236 (#8)</strong> y <strong>zPibu__ (#30)</strong> cubren los laterales.',
      'En el mediocampo, <strong>Juan_Martinez4 (#6)</strong>, <strong>RS32-DaniStone (#13)</strong>, <strong>CipriMancini (#32)</strong>, <strong>Buraa07 (#5)</strong> y <strong>Guiidow (#20)</strong> ofrecen variantes tácticas y físicas para cualquier sistema.',
      'Arriba, la línea de ataque sigue siendo letal: <strong>BlackPanther-CG (#11)</strong>, <strong>Lautavester7 (#7)</strong> y <strong>Lucasmati_akd (#9)</strong> son los encargados de romper redes en la categoría más competitiva del fútbol virtual argentino.',
      '16 jugadores. Una identidad. Bienvenidos a la nueva era de Top Secret FC. 🖤⭐',
    ],
    shareCaption: '🖤 TOP SECRET FC · PLANTEL 2026\n\nEste es el equipo que jugará la nueva temporada:\n\n🧤 #19 pauloco10 · #45 Woolfyboyzx2\n🔒 #3 Alexisraies23 · #4 Cabers14 · #21 AR-ELTIO · #31 Agubostero7\n↔️ #8 Huber236 · #30 zPibu__\n⚙️ #6 Juan_Martinez4 · #13 RS32-DaniStone · #32 CipriMancini · #5 Buraa07 · #20 Guiidow\n⚡ #11 BlackPanther-CG · #7 Lautavester7 · #9 Lucasmati_akd\n\n16 jugadores. Una misión. ⭐\n\n#TopSecretFC #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 PLANTEL 2026 · TOP SECRET FC\n\n16 jugadores. Una identidad. Una misión. ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #NuevaTemporada #VPN',
      x:  '🖤 Top Secret FC presenta el plantel 2026.\n\n16 jugadores listos para la élite del fútbol virtual argentino ⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
      fb: '🖤 PLANTEL 2026 · TOP SECRET FC\n\nEl club presenta oficialmente el plantel para la nueva temporada. Dieciséis jugadores comprometidos con el proyecto y listos para competir en la Primera División de la VPN.\n\n16 jugadores. Una identidad. Una misión. 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #EAFCClubsPro #VPN',
    },
  },
  {
    id: 'fichajes-t2-2026',
    pinned: false,
    category: 'Mercado',
    title: 'Tres incorporaciones para la Temporada 2',
    date: '2026-05-10',
    dateLabel: '10 de mayo de 2026',
    excerpt: 'Top Secret FC anuncia las altas para la nueva temporada: Cabers14, pauloco10 y AR-ELTIO se suman al plantel. Nuevo Secreto. Misma Misión.',
    image: 'logos/Fichajes.webp',
    body: [
      'Top Secret FC cierra su ventana de mercado para la Temporada 2 con tres incorporaciones que refuerzan el plantel de cara al debut en la Primera División de la VPN.',
      '<strong>#4 · Cabers14</strong> llega para puntalar la línea defensiva. Defensa central con presencia y capacidad para liderar la última línea en una categoría más exigente.',
      '<strong>#19 · pauloco10</strong> es la gran apuesta del club. Portero con un perfil moderno que llega a ocupar el arco en una categoría que exige reacciones al máximo nivel.',
      '<strong>#21 · AR-ELTIO</strong> completa el bloque defensivo. Su incorporación da más profundidad al backline y permite al cuerpo técnico rotar sin resignar intensidad.',
      'Las tres altas consolidan un plantel con mayor amplitud y competencia en cada línea. El mensaje es claro: <em>Nuevo Secreto. Misma Misión.</em>',
    ],
    shareCaption: '🖤 FICHAJES · TOP SECRET FC\n\nTres incorporaciones para la Temporada 2:\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión. ⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
    shareCaptions: {
      ig: '🖤 NUEVAS INCORPORACIONES · TOP SECRET FC\n\nTres refuerzos para la Temporada 2 ⭐\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión.\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Fichajes #EAFCClubsPro #NuevaTemporada',
      x:  '🖤 Top Secret FC anuncia tres incorporaciones para la Temporada 2.\n\n🔒 Cabers14 · pauloco10 · AR-ELTIO\n\nNuevo Secreto. Misma Misión. ⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
      fb: '🖤 FICHAJES · TOP SECRET FC\n\nEl club cierra su mercado para la Temporada 2 con tres incorporaciones que refuerzan defensiva y portería de cara al debut en Primera División VPN.\n\n🔒 #4 Cabers14\n🧤 #19 pauloco10\n🔒 #21 AR-ELTIO\n\nNuevo Secreto. Misma Misión. 🖤⭐\n\n#TopSecretFC #Fichajes #EAFCClubsPro',
    },
  },
  {
    id: 'kit-drop-2026',
    pinned: false,
    category: 'Indumentaria',
    title: 'Nuevas camisetas para la temporada 2026',
    date: '2026-05-06',
    dateLabel: '6 de mayo de 2026',
    excerpt: 'Top Secret FC presenta el nuevo kit oficial para la temporada 2026. Las camisetas que nos acompañarán en la VPN, la VPUG y el 11x11.',
    image: 'logos/2026 Kit Drop.png',
    body: [
      'Top Secret FC presenta oficialmente el nuevo kit para la temporada 2026. Un diseño que llega con fuerza en un momento especial: el debut del club en la Primera División de la VPN.',
      'Las nuevas camisetas nos acompañarán en todas las competencias del ciclo: la Liga VPN, la VPUG y el 11x11. Tres frentes, una sola identidad.',
      'El kit es más que indumentaria. Es la imagen con la que salimos a la cancha, la que representa al club en cada partido y en cada foto. Este diseño está a la altura del momento.',
      '¡A lucirlas en la cancha! 🖤⭐',
    ],
    shareCaption: '👕 NUEVAS CAMISETAS · TOP SECRET FC\n\nPresentamos el kit oficial para la temporada 2026 🖤⭐\n\nVPN · VPUG · 11x11\n\nSeguinos → @fctopsecret en IG y X · fb.com/topsecretfc\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
    shareCaptions: {
      ig: '👕 KIT DROP 2026 · TOP SECRET FC\n\nNuevas camisetas para una nueva era 🖤⭐\n\nVPN · VPUG · 11x11\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro #NuevaTemporada',
      x:  '👕 Top Secret FC presenta el kit oficial 2026.\n\nTres ligas, una identidad 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
      fb: '👕 NUEVAS CAMISETAS · TOP SECRET FC\n\nPresentamos el kit oficial para la temporada 2026. Las camisetas que nos acompañarán en la VPN, la VPUG y el 11x11.\n\nUn diseño a la altura de la nueva era del club 🖤⭐\n\nSeguinos en Instagram y X: @fctopsecret\n\n#TopSecretFC #KitDrop #EAFCClubsPro',
    },
  },
  {
    id: 'rebrand-2026',
    pinned: false,
    category: 'Institucional',
    title: 'Top Secret FC presenta su nueva identidad',
    date: '2026-05-06',
    dateLabel: '6 de mayo de 2026',
    excerpt: 'El club anuncia una renovación de su identidad visual. Una nueva era para Top Secret FC.',
    image: 'logos/Anuncio Rebrand.webp',
    body: [
      'Top Secret FC da un paso adelante y presenta oficialmente su nueva identidad visual. Un rediseño que refleja la evolución del club y su crecimiento dentro del fútbol virtual argentino.',
      'La nueva imagen llega en un momento bisagra: el club acaba de lograr el ascenso a la Primera División de la VPN y se prepara para debutar en la élite del fútbol virtual argentino.',
      'El rebrand es más que un cambio estético. Representa la ambición del club, su identidad y el camino que tiene por delante.',
      'Seguinos en nuestras redes: <a href="https://instagram.com/fctopsecret" target="_blank" rel="noopener">Instagram</a> · <a href="https://x.com/fctopsecret" target="_blank" rel="noopener">X</a> · <a href="https://facebook.com/topsecretfc" target="_blank" rel="noopener">Facebook</a>',
      '¡Bienvenidos a la nueva era de Top Secret FC!',
    ],
    shareCaption: '⭐ TOP SECRET FC · NUEVA IDENTIDAD\n\nEl club presenta su nueva imagen. Una nueva era comienza.\n\n📱 @fctopsecret en IG y X · fb.com/topsecretfc\n\n🖤⭐ #TopSecretFC #Rebrand #EAFCClubsPro',
    shareCaptions: {
      ig: '⭐ NUEVA IDENTIDAD · TOP SECRET FC\n\nEvolucionamos. Presentamos nuestra nueva imagen 🖤⭐\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Rebrand #EAFCClubsPro',
      x:  '⭐ Top Secret FC presenta su nueva identidad visual.\n\nUna nueva era comienza 🖤\n\nSeguinos → @fctopsecret\n\n#TopSecretFC #Rebrand',
      fb: '⭐ TOP SECRET FC · NUEVA IDENTIDAD\n\nEl club presenta oficialmente su nueva imagen visual. Un rediseño que refleja nuestra evolución y el camino que tenemos por delante.\n\nSeguinos en Instagram y X: @fctopsecret\n\n¡Bienvenidos a la nueva era! 🖤⭐\n\n#TopSecretFC #Rebrand #EAFCClubsPro',
    },
  },
  {
    id: 'equipo-temporada-vpn-2026',
    pinned: false,
    category: 'Distinción',
    title: 'Tres jugadores en el Equipo de la Temporada VPN',
    date: '2026-05-04',
    dateLabel: '4 de mayo de 2026',
    excerpt: 'La Liga VPN seleccionó a Lautavester7, cansitrGd22_ y BlackPanther-CG en su equipo ideal de la Temporada 1. Los tres delanteros del club firmaron números históricos.',
    image: 'logos/equipo-temporada-vpn.webp',
    body: [
      'La Liga VPN hizo oficial su Equipo de la Temporada 1 y Top Secret FC tuvo una participación histórica: tres jugadores seleccionados en el once ideal, todos delanteros.',
      'cansitrGd22_ fue el gran protagonista de la temporada con 64 goles y 22 asistencias en 49 partidos, cerrando con un rating promedio de 7.69 — el más alto del club. Sus números lo ubican como uno de los goleadores más letales de toda la liga.',
      'Lautavester7 completó una campaña de lujo con 41 goles y 18 asistencias en 52 partidos. Su versatilidad en el frente de ataque y su rendimiento constante (7.27 de promedio) lo hicieron un fijo en el esquema y merecedor del reconocimiento.',
      'BlackPanther-CG aportó profundidad y desequilibrio con 21 goles y 19 asistencias en 54 partidos — el más activo de los tres. Su capacidad de asociación y los centros al área fueron claves en el juego colectivo del equipo.',
      'El anuncio fue realizado oficialmente por la cuenta de VPN Argentina en X. Top Secret FC es el club con más representantes en el Equipo de la Temporada.',
    ],
    shareCaption: '🏆 ¡EQUIPO DE LA TEMPORADA VPN! 🏆\n\n3 jugadores de Top Secret FC en el XI ideal de la Liga VPN:\n\n⚡ #7 Lautavester7 — 41G · 18A · 7.27 rating\n⚡ #22 cansitrGd22_ — 64G · 22A · 7.69 rating\n⚡ #11 BlackPanther-CG — 21G · 19A · 6.84 rating\n\n🖤⭐ #TopSecretFC #VPN #EquipoDeLaTemporada',
    shareCaptions: {
      ig: '🏆 EQUIPO DE LA TEMPORADA · LIGA VPN\n\n3 de los nuestros en el XI ideal de la Temporada 1 🖤⭐\n\n⚡ Lautavester7 — 41G · 18A\n⚡ cansitrGd22_ — 64G · 22A\n⚡ BlackPanther-CG — 21G · 19A\n\n#TopSecretFC #VPN #EquipoDeLaTemporada #EAFCClubsPro',
      x:  '🏆 3 jugadores de Top Secret FC en el Equipo de la Temporada VPN\n\n⚡ Lautavester7 — 41G · 18A\n⚡ cansitrGd22_ — 64G · 22A\n⚡ BlackPanther-CG — 21G · 19A\n\n#TopSecretFC #VPN #EquipoDeLaTemporada',
      fb: '🏆 ¡EQUIPO DE LA TEMPORADA VPN! 🏆\n\nTop Secret FC tuvo 3 representantes en el once ideal de la Liga VPN Temporada 1. Un reconocimiento histórico para el club.\n\n⚡ Lautavester7 — 41 goles · 18 asistencias\n⚡ cansitrGd22_ — 64 goles · 22 asistencias\n⚡ BlackPanther-CG — 21 goles · 19 asistencias\n\n#TopSecretFC #VPN #EAFCClubsPro',
    },
  },
  {
    id: 'ascenso-primera-2025',
    pinned: false,
    category: 'Histórico',
    title: 'Ascendimos a Primera División',
    date: '2025-05-03',
    dateLabel: '3 de mayo de 2025',
    excerpt: 'Top Secret FC logró el ascenso a la Primera División de la VPN tras una campaña histórica. Un hito que marca el inicio de una nueva era para el club.',
    image: 'logos/Festejo Ascenso.webp',
    body: [
      'Top Secret FC escribió una de las páginas más importantes de su historia al coronarse campeón y obtener el ascenso a la Primera División de la VPN.',
      'Fue una temporada de entrega, trabajo y colectivo. El equipo demostró carácter en los momentos clave y supo imponerse ante rivales de mucho nivel para hacerse merecedor de este logro.',
      'El festejo no tardó en llegar. Los jugadores celebraron el hito con la alegría y la emoción que merece un logro de esta magnitud. Las imágenes del festejo quedaron grabadas en la memoria del club.',
      'A partir de esta temporada, Top Secret FC competirá en la élite del fútbol virtual argentino. El desafío es enorme, pero la base está construida: un plantel comprometido, una identidad clara y una hinchada que acompaña.',
      '¡Arriba Top Secret FC! ¡Primera División!',
    ],
    shareCaption: '🏆 ¡ASCENDIMOS A PRIMERA DIVISIÓN! 🏆\n\nTop Secret FC acaba de lograr uno de los hitos más importantes de su historia. Campaña perfecta, equipo comprometido, resultado histórico.\n\n¡A la Primera División de la VPN! 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
    shareCaptions: {
      ig: '🏆 ¡ASCENDIDOS A PRIMERA DIVISIÓN! 🏆\n\nCampaña histórica. Equipo comprometido. Un resultado que quedará para siempre en la memoria del club 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
      x:  '🏆 ¡Top Secret FC asciende a Primera División VPN!\n\nCampaña histórica. Gracias a todos los que acompañaron 🖤⭐\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso',
      fb: '🏆 ¡ASCENDIDOS A PRIMERA DIVISIÓN! 🏆\n\nTop Secret FC logró el ascenso a la Primera División de la VPN tras una campaña histórica. Un resultado que quedará para siempre en la historia del club.\n\nGracias a cada jugador, cada entrenamiento y cada partido. Este logro es de todos. ¡Arriba Top Secret FC!\n\n#TopSecretFC #VPN #PrimeraDivision #Ascenso #EAFCClubsPro',
    },
  },
];

// Solo la primera noticia con pinned:true queda fijada; las demás se desclavan.
const _pi = NOTICIAS.findIndex(n => n.pinned);
NOTICIAS.forEach((n, i) => { n.pinned = i === _pi; });
