// ─── TOP SECRET FC · Datos de partidos compartidos ───────────────────────────
// Importado por index.html. Para agregar partidos, editar estadisticas.html y actualizar este archivo.

const SEED_MATCHES = [

  // ── VPUG ──────────────────────────────────
  {rival:'Suda', league:'VPUG', date:'2025-03-02', match_result:'2-0', uploadedAt:'2025-03-02T00:00:00.000Z', notes:'',
  team_stats:{posesion:null,tiros:null,tiros_arco:null,goles_esperados:null,pases:null,precision_pases:null,entradas:null,entradas_exito:null,intercepciones:null,paradas:null,faltas:null,fuera_juego:null,corneres:null,regates_exito:null,precision_tiro:null},
  players:[
    {name:'Lautavester7',   matched:'Lautavester7',   rating:7.8, goals:1, assists:1, passes:21,  pass_accuracy:90, distance_km:18.4, sprints:null, tackles:1,  interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:7.2, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:7.6, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Team Valhala', league:'VPUG', date:'2025-03-03', match_result:'5-0', uploadedAt:'2025-03-03T01:00:00.000Z', notes:'',
  team_stats:{posesion:68,tiros:11,tiros_arco:null,goles_esperados:7.3,pases:242,precision_pases:87,entradas:19,entradas_exito:8,intercepciones:null,paradas:3,faltas:4,fuera_juego:2,corneres:4,regates_exito:95,precision_tiro:73},
  players:[
    {name:'Lautavester7',   matched:'Lautavester7',   rating:10.0, goals:3, assists:1, passes:16,  pass_accuracy:88, distance_km:17.9, sprints:null, tackles:6,  interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:7.4,  goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:7.4,  goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:8.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:8.0,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        rating:7.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:8.9,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:8.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:6.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'La Unión', league:'VPUG', date:'2025-03-04', match_result:'8-1', uploadedAt:'2025-03-04T00:00:00.000Z', notes:'',
  team_stats:{posesion:null,tiros:null,tiros_arco:null,goles_esperados:null,pases:null,precision_pases:null,entradas:null,entradas_exito:null,intercepciones:null,paradas:null,faltas:null,fuera_juego:null,corneres:null,regates_exito:null,precision_tiro:null},
  players:[
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:7.2,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:10.0, goals:4, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:9.5,  goals:2, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:9.0,  goals:1, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:10.0, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:8.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Buraa07',        matched:'Buraa07',        rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        rating:8.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:6.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:5.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'IACC Cantera', league:'VPUG', date:'2025-03-09', match_result:'2-4', uploadedAt:'2025-03-09T00:00:00.000Z', notes:'',
  team_stats:{posesion:57,tiros:6,tiros_arco:null,goles_esperados:2.9,pases:234,precision_pases:83,entradas:19,entradas_exito:5,intercepciones:null,paradas:2,faltas:1,fuera_juego:0,corneres:5,regates_exito:96,precision_tiro:83},
  players:[
    {name:'Lautavester7',   matched:'Lautavester7',   rating:6.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:8.5,  goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',       matched:'Huber236',       rating:6.7,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:8.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.2,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        rating:7.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:9.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:6.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:4.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── 11x11 ─────────────────────────────────
  {rival:'Los Picantes', league:'11x11', date:'2025-03-03', match_result:'7-0', uploadedAt:'2025-03-03T00:00:00.000Z', notes:'',
  team_stats:{posesion:55,tiros:11,tiros_arco:10,goles_esperados:5.3,pases:199,precision_pases:86,entradas:28,entradas_exito:3,intercepciones:19,paradas:1,faltas:1,fuera_juego:0,corneres:4,regates_exito:93,precision_tiro:91},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:8.5,  goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:10.0, goals:2, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:10.0, goals:3, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:7.4,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:9.0,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:8.5,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:8.3,  goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.6,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:6.9,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Talleres R eSp', league:'11x11', date:'2025-03-05', match_result:'6-1', uploadedAt:'2025-03-05T00:00:00.000Z', notes:'',
  team_stats:{posesion:64,tiros:13,tiros_arco:null,goles_esperados:6.9,pases:240,precision_pases:90,entradas:18,entradas_exito:4,intercepciones:28,paradas:0,faltas:1,fuera_juego:3,corneres:2,regates_exito:92,precision_tiro:62},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:9.5,  goals:0, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:9.0,  goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:10.0, goals:4, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:7.7,  goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:9.3,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:7.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:8.0,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:5.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Inst. Senior', league:'11x11', date:'2025-03-05', match_result:'6-0', uploadedAt:'2025-03-05T01:00:00.000Z', notes:'',
  team_stats:{posesion:62,tiros:14,tiros_arco:null,goles_esperados:6.1,pases:208,precision_pases:88,entradas:25,entradas_exito:9,intercepciones:18,paradas:2,faltas:0,fuera_juego:0,corneres:4,regates_exito:91,precision_tiro:64},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:8.0,  goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:10.0, goals:4, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:8.7,  goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:9.0,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.6,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:9.4,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:7.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Talleres Reserva', league:'11x11', date:'2025-03-10', match_result:'0-1', uploadedAt:'2025-03-10T00:00:00.000Z', notes:'',
  team_stats:{posesion:65,tiros:7,tiros_arco:null,goles_esperados:3.9,pases:226,precision_pases:87,entradas:22,entradas_exito:6,intercepciones:12,paradas:1,faltas:0,fuera_juego:0,corneres:7,regates_exito:93,precision_tiro:86},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:7.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:6.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:6.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:6.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:8.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone', matched:'RS32-DaniStone', rating:7.6,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:6.9,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:8.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:5.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Estudiantes RC', league:'11x11', date:'2025-03-10', match_result:'4-0', uploadedAt:'2025-03-10T01:00:00.000Z', notes:'',
  team_stats:{posesion:67,tiros:10,tiros_arco:null,goles_esperados:6.1,pases:214,precision_pases:90,entradas:25,entradas_exito:10,intercepciones:17,paradas:1,faltas:0,fuera_juego:1,corneres:2,regates_exito:92,precision_tiro:80},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:7.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:8.3,  goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:9.8,  goals:2, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:6.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:8.8,  goals:0, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:8.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone', matched:'RS32-DaniStone', rating:7.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.9,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:8.8,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:8.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   rating:7.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── VPN ───────────────────────────────────
  {rival:'Los Lesionados', league:'VPN', date:'2025-03-09', match_result:'0-1', uploadedAt:'2025-03-09T01:00:00.000Z', notes:'',
  team_stats:{posesion:60,tiros:8,tiros_arco:null,goles_esperados:3.3,pases:219,precision_pases:86,entradas:18,entradas_exito:6,intercepciones:18,paradas:1,faltas:0,fuera_juego:0,corneres:3,regates_exito:92,precision_tiro:63},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:6.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:6.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',       matched:'Huber236',       rating:6.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:7.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:7.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:8.2,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:6.0,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Olimpo Esports', league:'VPN', date:'2025-03-09', match_result:'3-3', uploadedAt:'2025-03-09T02:00:00.000Z', notes:'',
  team_stats:{posesion:62,tiros:4,tiros_arco:null,goles_esperados:2.5,pases:212,precision_pases:83,entradas:14,entradas_exito:6,intercepciones:14,paradas:3,faltas:1,fuera_juego:3,corneres:0,regates_exito:95,precision_tiro:75},
  players:[
    {name:'zPibu__',        matched:'zPibu__',        rating:7.5,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   rating:7.7,  goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   rating:8.5,  goals:1, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',       matched:'Huber236',       rating:6.1,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   rating:7.9,  goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', rating:6.9,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        rating:7.8,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    rating:7.4,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',rating:7.9,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  rating:7.7,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', rating:5.3,  goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── NUEVOS: VPUG Fecha 7 y 8 ─────────────
  {rival:'Team Ceniza', league:'VPUG', date:'2025-03-11', match_result:'2-2', uploadedAt:'2025-03-11T22:30:00.000Z', notes:'',
  team_stats:{posesion:51,tiros:8,tiros_arco:null,goles_esperados:4.3,pases:168,precision_pases:82,entradas:21,entradas_exito:3,intercepciones:25,paradas:2,faltas:0,fuera_juego:2,corneres:3,regates_exito:96,precision_tiro:100},
  players:[
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lucasmati_akd',  matched:'Lucasmati_akd',  played_pos:'EI',  rating:6.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'DC',  rating:8.1, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:7.9, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFC', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFD', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:4.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Real Marcianos', league:'VPUG', date:'2025-03-12', match_result:'7-1', uploadedAt:'2025-03-12T22:30:00.000Z', notes:'',
  team_stats:{posesion:52,tiros:11,tiros_arco:null,goles_esperados:3.4,pases:184,precision_pases:86,entradas:24,entradas_exito:5,intercepciones:22,paradas:0,faltas:1,fuera_juego:2,corneres:2,regates_exito:93,precision_tiro:82},
  players:[
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'EI',  rating:10.0, goals:4, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   played_pos:'DC',  rating:10.0, goals:2, assists:3, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:6.9, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   played_pos:'MCI', rating:9.6, goals:0, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:8.6, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:7.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFC', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFD', rating:8.0, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:5.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── NUEVOS: 11x11 Fecha 7 y 8 ────────────
  {rival:'Escuela Vieja', league:'11x11', date:'2025-03-12', match_result:'1-0', uploadedAt:'2025-03-12T23:00:00.000Z', notes:'',
  team_stats:{posesion:58,tiros:4,tiros_arco:null,goles_esperados:2.1,pases:179,precision_pases:83,entradas:18,entradas_exito:7,intercepciones:23,paradas:5,faltas:0,fuera_juego:1,corneres:4,regates_exito:93,precision_tiro:100},
  players:[
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'EI',  rating:6.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   played_pos:'DC',  rating:7.1, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   played_pos:'MCI', rating:7.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFC', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFD', rating:8.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'Team Valhalla', league:'11x11', date:'2025-03-12', match_result:'6-1', uploadedAt:'2025-03-12T23:30:00.000Z', notes:'',
  team_stats:{posesion:62,tiros:20,tiros_arco:null,goles_esperados:9.5,pases:196,precision_pases:84,entradas:26,entradas_exito:8,intercepciones:16,paradas:1,faltas:1,fuera_juego:1,corneres:10,regates_exito:91,precision_tiro:85},
  players:[
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:8.3, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'EI',  rating:7.6, goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',   matched:'cansitrGd22_',   played_pos:'DC',  rating:10.0, goals:5, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:7.7, goals:0, assists:3, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',   matched:'CipriMancini',   played_pos:'MCI', rating:7.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:7.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:9.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFC', rating:8.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFD', rating:8.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:6.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── NUEVOS: VPN Fecha 3 y 4 ──────────────
  {rival:'Suda Esports', league:'VPN', date:'2025-03-11', match_result:'0-0', uploadedAt:'2025-03-11T23:00:00.000Z', notes:'',
  team_stats:{posesion:44,tiros:5,tiros_arco:null,goles_esperados:1.4,pases:163,precision_pases:81,entradas:23,entradas_exito:6,intercepciones:23,paradas:5,faltas:1,fuera_juego:1,corneres:5,regates_exito:94,precision_tiro:100},
  players:[
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lucasmati_akd',  matched:'Lucasmati_akd',  played_pos:'EI',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'DC',  rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:6.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFC', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFD', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:8.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  {rival:'4BDOMIFL4NES', league:'VPN', date:'2025-03-11', match_result:'2-0', uploadedAt:'2025-03-11T23:30:00.000Z', notes:'',
  team_stats:{posesion:46,tiros:7,tiros_arco:null,goles_esperados:3.1,pases:128,precision_pases:74,entradas:34,entradas_exito:6,intercepciones:20,paradas:7,faltas:1,fuera_juego:0,corneres:2,regates_exito:89,precision_tiro:57},
  players:[
    {name:'Juan_Martinez4', matched:'Juan_Martinez4', played_pos:'MCD', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lucasmati_akd',  matched:'Lucasmati_akd',  played_pos:'EI',  rating:7.4, goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',   matched:'Lautavester7',   played_pos:'DC',  rating:7.3, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG',matched:'BlackPanther-CG', played_pos:'ED',  rating:6.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',        matched:'Guiidow',        played_pos:'MCD', rating:8.4, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',        matched:'zPibu__',        played_pos:'DFI', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',    matched:'Agubostero7',    played_pos:'DCI', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23',matched:'Alexiisraiies23',played_pos:'DFC', rating:8.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',  matched:'Zurdo-_CABJ12',  played_pos:'DFD', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',   matched:'Woolfyboyzx2',   played_pos:'PO',  rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // ── VPN ──────────────────────────────────────────────────────────────
  // Fecha 5 - All Boys - 16 Mar (Local, 2-1, Victoria)
  {rival:'All Boys', league:'VPN', date:'2026-03-16', match_result:'2-1', uploadedAt:'2026-03-16T00:00:00.000Z', notes:'',
  team_stats:{posesion:66,tiros:4,tiros_arco:null,goles_esperados:2.0,pases:212,precision_pases:86,entradas:15,entradas_exito:5,intercepciones:null,paradas:1,faltas:2,fuera_juego:5,corneres:1,regates_exito:null,precision_tiro:50},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.8, goals:0, assists:1, passes:22,  pass_accuracy:86,  distance_km:null, sprints:null, tackles:1,  interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'EI',  rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:8.0, goals:1, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:7.9, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone',  matched:'RS32-DaniStone',  played_pos:'MCD', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'DFI', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 6 - Ferro eSp - 16 Mar (Visita, 0-0, Empate)
  {rival:'FERRO', league:'VPN', date:'2026-03-16', match_result:'0-0', uploadedAt:'2026-03-16T00:00:00.000Z', notes:'',
  team_stats:{posesion:58,tiros:1,tiros_arco:1,goles_esperados:0.6,pases:208,precision_pases:82,entradas:27,entradas_exito:6,intercepciones:null,paradas:3,faltas:0,fuera_juego:1,corneres:0,regates_exito:null,precision_tiro:100},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.7, goals:0, assists:0, passes:25,  pass_accuracy:88,  distance_km:null, sprints:null, tackles:3,  interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'EI',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:6.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone',  matched:'RS32-DaniStone',  played_pos:'MCD', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'DFI', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:7.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 7 - La ResaKa - 18 Mar (Local, 2-1, Victoria)
  {rival:'La Resaca', league:'VPN', date:'2026-03-18', match_result:'2-1', uploadedAt:'2026-03-18T00:00:00.000Z', notes:'',
  team_stats:{posesion:50,tiros:2,tiros_arco:2,goles_esperados:1.2,pases:180,precision_pases:84,entradas:19,entradas_exito:4,intercepciones:null,paradas:3,faltas:0,fuera_juego:2,corneres:2,regates_exito:null,precision_tiro:100},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.2, goals:0, assists:0, passes:24,  pass_accuracy:83,  distance_km:19.3, sprints:null, tackles:0,  interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:6.8, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:8.3, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.4, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:6.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 8 - Alte Brown - 18 Mar (Visita, 5-0, Victoria)
  {rival:'Almirante Brown eSport', league:'VPN', date:'2026-03-18', match_result:'5-0', uploadedAt:'2026-03-18T00:00:00.000Z', notes:'',
  team_stats:{posesion:59,tiros:11,tiros_arco:null,goles_esperados:5.7,pases:196,precision_pases:90,entradas:23,entradas_exito:6,intercepciones:null,paradas:2,faltas:1,fuera_juego:3,corneres:2,regates_exito:null,precision_tiro:73},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.6, goals:0, assists:0, passes:27,  pass_accuracy:81,  distance_km:18.5, sprints:null, tackles:1,  interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:8.2, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:9.7, goals:3, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:7.8, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:8.2, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:8.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:8.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:8.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},


  // ── 11x11 ─────────────────────────────────────────────────────────────
  // Fecha 9 - Dep Ballester - 17 Mar (Visita, 2-2, Empate)
  {rival:'Deportivo Ballester', league:'11x11', date:'2026-03-17', match_result:'2-2', uploadedAt:'2026-03-17T00:00:00.000Z', notes:'',
  team_stats:{posesion:58,tiros:12,tiros_arco:null,goles_esperados:4.3,pases:196,precision_pases:78,entradas:20,entradas_exito:7,intercepciones:null,paradas:2,faltas:0,fuera_juego:3,corneres:5,regates_exito:null,precision_tiro:33},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.7, goals:0, assists:1, passes:26,  pass_accuracy:77,  distance_km:18.8, sprints:null, tackles:1,  interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'EI',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'DC',  rating:8.2, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:6.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFI', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:8.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 10 - Olimpo eSports - 17 Mar (Local, 2-1, Victoria)
  {rival:'Olimpo Esports', league:'11x11', date:'2026-03-17', match_result:'2-1', uploadedAt:'2026-03-17T00:00:00.000Z', notes:'',
  team_stats:{posesion:61,tiros:5,tiros_arco:3,goles_esperados:1.4,pases:199,precision_pases:84,entradas:18,entradas_exito:4,intercepciones:null,paradas:3,faltas:1,fuera_juego:0,corneres:0,regates_exito:null,precision_tiro:60},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.9, goals:0, assists:0, passes:37,  pass_accuracy:70,  distance_km:18.3, sprints:null, tackles:1,  interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'EI',  rating:7.0, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'DC',  rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:5.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:8.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFI', rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.9, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:8.3, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:5.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},


  // Fecha 11 - Acosta Beef - 19 Mar (Visita, 6-0, Victoria)
  {rival:'Acosta Beef Esports', league:'11x11', date:'2026-03-19', match_result:'6-0', uploadedAt:'2026-03-19T00:00:00.000Z', notes:'',
  team_stats:{posesion:61,tiros:12,tiros_arco:null,goles_esperados:5.8,pases:225,precision_pases:86,entradas:16,entradas_exito:2,intercepciones:null,paradas:2,faltas:2,fuera_juego:0,corneres:3,regates_exito:null,precision_tiro:67},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:8.4, goals:0, assists:1, passes:37,  pass_accuracy:78,  distance_km:19.3, sprints:null, tackles:0,  interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:7.3, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:10.0,goals:4, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:8.6, goals:2, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:8.4, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone',  matched:'RS32-DaniStone',  played_pos:'MCD', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFC', rating:7.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'DFD', rating:9.0, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 12 - IACC Cantera - 19 Mar (Local, 2-1, Victoria)
  {rival:'IACC Cantera', league:'11x11', date:'2026-03-19', match_result:'2-1', uploadedAt:'2026-03-19T00:00:00.000Z', notes:'',
  team_stats:{posesion:71,tiros:10,tiros_arco:7,goles_esperados:5.1,pases:239,precision_pases:91,entradas:27,entradas_exito:4,intercepciones:null,paradas:5,faltas:3,fuera_juego:0,corneres:4,regates_exito:null,precision_tiro:70},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.6, goals:0, assists:1, passes:21,  pass_accuracy:95,  distance_km:18.4, sprints:null, tackles:0,  interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:7.7, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:8.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'RS32-DaniStone',  matched:'RS32-DaniStone',  played_pos:'MCD', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:8.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFC', rating:7.7, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'DFD', rating:7.5, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},


  // Fecha 9 VPUG - Germinal eSports - 24 Mar (Local, 3-2, Victoria)

  // Fecha 9 - Germinal eSports - 24 Mar (Local, 3-2, Victoria)
  {rival:'Germinal eSports', league:'VPUG', date:'2026-03-24', match_result:'3-2', uploadedAt:'2026-03-24T00:00:00.000Z', notes:'',
  team_stats:{posesion:56,tiros:9,tiros_arco:null,goles_esperados:3.8,pases:192,precision_pases:87,entradas:20,entradas_exito:4,intercepciones:null,paradas:1,faltas:2,fuera_juego:2,corneres:2,regates_exito:91,precision_tiro:67},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.6, goals:0, assists:1, passes:28, pass_accuracy:79, distance_km:18.8, sprints:null, tackles:2, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:6.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:9.6, goals:3, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:7.1, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:7.7, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:8.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:6.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DCI', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFD', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:5.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},


  // Fecha 13 - AlToke Perro - 24 Mar (Visita, 2-2, Empate)
  {rival:'Altoke Perro', league:'11x11', date:'2026-03-24', match_result:'2-2', uploadedAt:'2026-03-24T00:00:00.000Z', notes:'',
  team_stats:{posesion:61,tiros:6,tiros_arco:null,goles_esperados:2.9,pases:224,precision_pases:86,entradas:27,entradas_exito:5,intercepciones:null,paradas:3,faltas:1,fuera_juego:0,corneres:2,regates_exito:93,precision_tiro:67},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:8.3, goals:0, assists:1, passes:31, pass_accuracy:77, distance_km:18.6, sprints:null, tackles:1, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:7.2, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:8.5, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:7.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:6.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DCI', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFD', rating:6.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:5.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 14 - All Boys - 24 Mar (Local, 1-0, Victoria)
  {rival:'All Boys', league:'11x11', date:'2026-03-24', match_result:'1-0', uploadedAt:'2026-03-24T00:00:00.000Z', notes:'',
  team_stats:{posesion:70,tiros:2,tiros_arco:null,goles_esperados:0.8,pases:242,precision_pases:86,entradas:17,entradas_exito:4,intercepciones:null,paradas:0,faltas:1,fuera_juego:1,corneres:1,regates_exito:95,precision_tiro:50},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.5, goals:0, assists:0, passes:32, pass_accuracy:78, distance_km:18.6, sprints:null, tackles:2, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:6.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:7.4, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:8.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:7.7, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DCI', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Huber236',        matched:'Huber236',        played_pos:'DFD', rating:6.8, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},



  // Fecha 9 - Sub21 CF - 25 Mar (Local, 1-1, Empate)
  {rival:'Sub21 CF', league:'VPN', date:'2026-03-25', match_result:'1-1', uploadedAt:'2026-03-25T00:00:00.000Z', notes:'',
  team_stats:{posesion:60,tiros:3,tiros_arco:null,goles_esperados:0.9,pases:206,precision_pases:83,entradas:19,entradas_exito:6,intercepciones:null,paradas:2,faltas:0,fuera_juego:0,corneres:2,regates_exito:87,precision_tiro:33},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.7, goals:0, assists:1, passes:22, pass_accuracy:73, distance_km:18.6, sprints:null, tackles:1, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:6.7, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 10 - Parke Avellane - 25 Mar (Local, 3-1, Victoria)
  {rival:'Parke Avellane', league:'VPN', date:'2026-03-25', match_result:'3-1', uploadedAt:'2026-03-25T01:00:00.000Z', notes:'',
  team_stats:{posesion:52,tiros:4,tiros_arco:null,goles_esperados:2.6,pases:189,precision_pases:79,entradas:24,entradas_exito:3,intercepciones:null,paradas:1,faltas:1,fuera_juego:0,corneres:1,regates_exito:92,precision_tiro:75},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.6, goals:0, assists:0, passes:27, pass_accuracy:81, distance_km:18.9, sprints:null, tackles:1, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:7.1, goals:0, assists:2, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:8.1, goals:2, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.7, goals:1, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:8.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:7.5, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:7.7, goals:0, assists:1, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

  // Fecha 10 VPUG - Olimpo eSports - 25 Mar (Visita, 0-1, Derrota)
  {rival:'Olimpo eSports', league:'VPUG', date:'2026-03-25', match_result:'0-1', uploadedAt:'2026-03-25T02:00:00.000Z', notes:'',
  team_stats:{posesion:55,tiros:2,tiros_arco:null,goles_esperados:0.5,pases:203,precision_pases:81,entradas:19,entradas_exito:4,intercepciones:null,paradas:2,faltas:1,fuera_juego:0,corneres:1,regates_exito:93,precision_tiro:50},
  players:[
    {name:'Juan_Martinez4',  matched:'Juan_Martinez4',  played_pos:'MCD', rating:7.0, goals:0, assists:0, passes:26, pass_accuracy:69, distance_km:19.4, sprints:null, tackles:0, interceptions:null},
    {name:'Lautavester7',    matched:'Lautavester7',    played_pos:'EI',  rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'cansitrGd22_',    matched:'cansitrGd22_',    played_pos:'DC',  rating:5.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'BlackPanther-CG', matched:'BlackPanther-CG', played_pos:'ED',  rating:6.4, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'CipriMancini',    matched:'CipriMancini',    played_pos:'MCI', rating:7.3, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Guiidow',         matched:'Guiidow',         played_pos:'MCD', rating:7.9, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'zPibu__',         matched:'zPibu__',         played_pos:'DFI', rating:6.7, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Agubostero7',     matched:'Agubostero7',     played_pos:'DCI', rating:7.2, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Alexiisraiies23', matched:'Alexiisraiies23', played_pos:'DFC', rating:8.0, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Zurdo-_CABJ12',   matched:'Zurdo-_CABJ12',   played_pos:'DFD', rating:6.6, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
    {name:'Woolfyboyzx2',    matched:'Woolfyboyzx2',    played_pos:'POR', rating:6.1, goals:0, assists:0, passes:null, pass_accuracy:null, distance_km:null, sprints:null, tackles:null, interceptions:null},
  ]},

];


export { SEED_MATCHES };
